### ISSUE TITLE
BasicSelect/Combobox: unique key error

### ISSUE THREAD

**Issue by dkorsun36** [gazprom-neft/consta-uikit#1000]
Добрый день!

Используем в проекте BasicSelect и Combobox и получаем список в котором значения одинаковые, а айдишники у элементов разные, так вот из-за этого получаем многочисленные предупреждения, что тормозит работу программы 
![image](https://user-images.githubusercontent.com/75089644/112134244-9512c280-8bdd-11eb-8808-53242557adb2.png)

Структура у этих компонентов такая {label: string, value: string (uuid)} и в key подставляется именно label.
 Просьба для key забирать значение value в котором хранится айдишник. а не забирать из label.

Заранее спасибо.

**Comment by monolithed** [comment]
Брать key из value еще более не правильно, там пересечений больше

**Comment by dkorsun36** [comment]
Тогда лучше сделать новый параметр в который можно передавать key

**Comment by monolithed** [comment]
Можно как вариант добавить в key префикс label.options если он есть.

**Comment by gizeasy** [comment]
я в курсе этой проблемы, в скоре возмемся. Решим пропосом getKey, функция на входд примет item и должна вернуть уникатльный ключ
