### ISSUE TITLE
Ошибка при сборке. TabsTab.css

### ISSUE THREAD

**Issue by wolfling-jim** [gazprom-neft/consta-uikit#1001]
При сборке приложения (npm run build) происходит ошибка.
`Creating an optimized production build...
Failed to compile.

```
./node_modules/@consta/uikit/__internal__/src/components/Tabs/Tab/TabsTab.css
ParserError: Syntax Error at line: 1, column 23


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cpunsi-fe-main@1.2.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cpunsi-fe-main@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sergei\AppData\Roaming\npm-cache\_logs\2021-03-23T11_29_28_087Z-debug.log
```

Ошибка решается добавлением в TabsTab.css отступов перед умножением на -1:`
```
 .TabsTab::before {
    content: '';
    position: absolute;
    top: 0;
    right: calc(var(--space-2xs) * -1);
    left: calc(var(--space-2xs) * -1);
    bottom: 0;
    display: block;
    border-radius: var(--control-radius);
 }
```

**Comment by monolithed** [comment]
[Исправлено](https://github.com/gazprom-neft/consta-uikit/blob/2c8adee29dbd2d6190d18206f0bda4da83166766/src/components/Tabs/Tab/TabsTab.css#L25)

**Comment by wolfling-jim** [comment]
Приветсвую!
Проблема появилась вновь.
Версия: 1.11.13

**Comment by monolithed** [comment]
@gizeasy подтверждаю

1.11.13:

<img width="541" alt="Снимок экрана 2021-05-21 в 22 40 22" src="https://user-images.githubusercontent.com/803674/119190368-ecba9680-ba85-11eb-9143-fd6c822b31f5.png">

1.11.16:

<img width="505" alt="Снимок экрана 2021-05-21 в 22 43 45" src="https://user-images.githubusercontent.com/803674/119190454-0cea5580-ba86-11eb-9068-17bb1d690d0e.png">

**Comment by gizeasy** [comment]
В следующем релизе ошибка будет исправлена
