### ISSUE TITLE
FR: Sidebar component

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1006]
Хочу иметь возможность контролировать ширину.
Хочу, чтобы нажатие снаружи не закрывало `Sidebar`, а вообще не перехватывалось (продолжало обрабатываться другими компонентами).

**Comment by andreynovikov** [comment]
Попробовал поиграться с обработчиками событий, но судя по https://github.com/gazprom-neft/consta-uikit/blob/14e3f17d6ef79058b6642b24d70c5a362fdbab62/src/components/Sidebar/Sidebar.tsx#L65-L78
их недолжно быть, чтобы событие не обрабатывалось, но они устанавливаются в пустые обработчики. Возможно это имеет смысл делать только если `hasOverlay = true`?

Ещё заметил, что если при открытом `Sidebar` менять его содержимое, то он мерцает (исчезает на долю секунды и снова появляется).

**Comment by kolebayev** [comment]
@andreynovikov привет, можешь рассказать подробно про контекст с шириной? Для чего ты хочешь ей рулить?

**Comment by andreynovikov** [comment]
У меня есть список в виде таблицы. При нажатии на элемент списка я открываю сайдбар и показываю в нём подробное описание этого элемента. Описание большое, поэтому в узком сайдбаре смотрится плохо, я его принудительно делаю гораздо шире, пока жёстко задал ширину, но есть мысль вычислять её динамически в зависимости от содержимого таблицы. Я понимаю, что сайдбар задумывался не для этого, но ничего более подходящего я не придумал.

**Comment by Lyubavskaya** [comment]
Будет реализовано в https://github.com/gazprom-neft/consta-uikit/issues/1142
Для сайдбара это антипаттерн.
