### ISSUE TITLE
landing: разбить бандл лэндоса

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1008]
Говорят, лендос на телефонах грузится ощутимо долго. В целом ожидаемо, только папка с графикой под переключение тем весит 14 мб. Эти картинки нам нужны все, поэтому предлагаю разбить бандл на 2 куска так:
1. вся верстка и логика + тема gpnDefault и графика под нее
2. остальные гпн темы (темные) + алюмикель и ва-банк + графика под них

После первого рендера, пока пользователь изучает страницу и скролит туда-сюда с контентом из п.1, успеем подгрузить второстепенные навороты из п.2

**Comment by kolebayev** [comment]
Посмотрел в дев тулзах, в каком-то виде это уже реализоано, но не понял по какому принципу разбиение кода

**Comment by gizeasy** [comment]
разбито на то что в node_modules и на то что в src

**Comment by gizeasy** [comment]
проверить на медленном интернете, результат задачи придумать как разбить бандл еще более оптимально

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/118247290-affe0680-b4ab-11eb-8320-3f9eb3f444f1.png)

сейчас работате так 
### js 
* 73.08 KB - все что в нод модулях, сам реакт, конста, и прочее
* 25.79 KB - код проекта
### css 
* 10.2 KB  - css из компонетов в нод модулях, по факту все компоненты из консты и дефольные темы
* 9.07 KB - css проекта

по размерам файлов, я пы не сказал что грузиться медленно, все должно быть очень быстро
скорее всего нет gzip на сервере, без него размеры сильно отличаются

* 10.2 KB -> 72 KB
*  9.07 KB -> 67 RB
* 73.08 KB -> 241 KB
* 25.79 KB -> 123 KB
