### ISSUE TITLE
Table: сортировка по-умолчанию

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1033]
Если загружаемые данные уже отсортированы по какому-то столбцу, хотелось бы иметь способ сказать об этом таблице, чтобы она нарисовала правильный значок сортировки. Мне кажется, проще всего это было бы указывать свойством колонки в массиве `columns`.

**Comment by andreynovikov** [comment]
А ещё хочется иметь возможность выбирать для каждого столбца, с чего начинать сортировку - с ASC или DESC. Для числовых столбцов часто нужнее сортировать по DESC, приходится делать два клика.

**Comment by gizeasy** [comment]
`ASC` `DESC` `UNSORTED?`
