### ISSUE TITLE
components: Добавить тени во все компоненты в Figma

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1054]
Подзадачи:

Завести стили на тени в каждой из цветовых тем в фигме и оставить объяснение в виде небольшой доки
- [x] default
- [x] dark
- [x] display

- [ ] Применить тени ко всем компонентам в UI-kit'e 

- [ ] сделать релиз цветовых библиотек и обновленного UI-kit'a (в день общих релизов)

**Comment by kolebayev** [comment]
вопросы по теням к @schurf-des
