### ISSUE TITLE
landing: Корректировки в лэндинге

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1063]
1. Более заметная ссылка на телеграм-канал на лендинге
2. И яндекс, и гугл странно индексируют тайтл лендоса 

~~На гитхабе в readme нужно добавить ссылку на сайт Consta и ссылку на телеграм-канал с релизами~~

~~В readme добавить пару слов про дизайн-систему. Сейчас разработчик, который приходит на гитхаб, вообще не видит, с чем он имеет дело)~~

**Comment by Lyubavskaya** [comment]
есть версия, что тайтл очень короткий и очень низко

и дескрпшн тоже

<title>Consta</title>

было бы круто это поправить, например, так

<title>Дизайн-система Consta</title>

или так

<title>Сайт дизайн-системы Consta</title>

и в  <meta name="description"> написать три-четыре предложения

**Comment by schurf-des** [comment]
Последние два пункта вынес в #1069
