### ISSUE TITLE
Tabs: добавить вертикальный вид табов

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1072]
Дизайн: https://www.figma.com/community/file/853774806786762374

**Comment by gizeasy** [comment]
Модификатор должен принимать vertical или horisontal, по умолчанию horisontal

**Comment by itsmealbina** [comment]
https://consta-uikit-git-dev-consta.vercel.app/?path=/story/components-tabs--playground
1. Вертикальная линия налезает на пункты табов 
Скрин:http://s.csssr.ru/UFALX8YMV/20210817_172417.jpg 
Например на разрешении для iphone 5/se
2. Линия для выбранного таба становится короткой при смене linePosition, если fitMode выбран dropdown
Скринкаст: http://s.csssr.ru/UFALX8YMV/Screencast_17-06_17-08-2021.mp4
3. Поправить вертикальные табы при размере m
Макет - отступ 16. Скрин: http://s.csssr.ru/UFALX8YMV/20210817_171507.jpg
Стенд - отступ 12. Скрин http://s.csssr.ru/UFALX8YMV/20210817_171629.jpg
4. При изменении размеров может длина для 1го пункта таба может сохраняться от предыдущего
Скрин: http://s.csssr.ru/UFALX8YMV/20210818_110916.jpg
Скринкаст: http://s.csssr.ru/UFALX8YMV/Screencast_11-11_18-08-2021.mp4
