### ISSUE TITLE
Text: Свойство width принимает только значение default

### ISSUE THREAD

**Issue by afbagautdinov** [gazprom-neft/consta-uikit#1074]
Для свойство width нельзя задать значение, кроме default.

Добавить возможность задавать численное и/или текстовое значение

**Comment by gizeasy** [comment]
вы можете воспользоваться интерфейсом className, и накинуть на блок `Text` свой блок `MyBlock`
и уже выставить ширину в своем блоке css свойствами

**Comment by gizeasy** [comment]
или можно воспользоваться интерфейсом style

**Comment by gizeasy** [comment]
@afbagautdinov удалось ли решить вашу проблему?

**Comment by afbagautdinov** [comment]
спасибо, проблема решена. issue в первую очередь связано с несоответствием в документации

_width - Ширина контейнера с текстом_

и пожеланием для дальнейшего развития функциональности

**Comment by Lyubavskaya** [comment]
Нужно просто убрать описание свойства width

**Comment by arhayka** [comment]
https://github.com/gazprom-neft/consta-uikit/pull/1288
