### ISSUE TITLE
Text: view - linkMinor и view - link, underline

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1081]
пордчеркивания и курсор поинтер нужны или нет
underline

**Comment by kolebayev** [comment]
cursor: pointer
андерлайн отключаем

**Comment by gizeasy** [comment]
при view = linkMinor / view добавить cursor поинтер
добавить модификатор underline

**Comment by gizeasy** [comment]
> cursor: pointer
> андерлайн отключаем

кажется что cursorPointer тоже должен быть отключаем. или вообще отсуствует, так как всегда его можно на проекте прикрутить, а вот если он будет с модификатором view то уже ни как не отключишь его без костылей
