### ISSUE TITLE
Skeleton: Разработать компонент

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1084]
[идея в фигме](https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=1294%3A3616)

_Originally posted by @kolebayev in https://github.com/gazprom-neft/consta-uikit/issues/918#issuecomment-828393483_

**Comment by nekitk** [comment]
Пример анимации блоков скелетона по отдельности: https://codepen.io/kolebayev/pen/ExZJeXL

**Comment by nekitk** [comment]
Варианты реализации общего градиента:
* SVG + userSpaceOnUse (но с позиционированием элементов в SVG будут проблемы)

**Comment by nekitk** [comment]
## Анимация

Для анимации предлагаю использовать background-attachment: fixed, см. [пример](https://codepen.io/nekitk/pen/NWjgYLw).

Анимация загрузки бегает по всей странице, элементы при этом будут без проблем синхронизироваться.

Нюансы и ограничения:
* Скорость анимации приходится тюнить под разные разрешения медиа-запросами. Если использовать одну скорость, то либо на десктопе будет слишком быстро, либо на мобилках слишком медленно из-за того, что по ширине анимация занимает весь экран.
* Анимация будет синхронизироваться только если элементы добавились на экран одновременно. Если элемент добавится динамически, у него анимация будет идти по своему циклу. Т.к. это элементы загрузки, то, кажется, они в большинстве кейсов будут появляться на странице одновременно.
* Элементы не стоит модифицировать transform-ом, т.к. анимация будет играть с таким таймингом, как будто элемент не трансформировался. Из-за этого элементы с трансформом будут выглядеть несинхронизированно с остальными.

## Компоненты

Для удобства собирания скелетонов предлагаю следующий набор компонентов

### Фигуры

1. Brick (пропсы: width, height)
2. Circle (пропсы: size)
3. Text (пропсы: rows, fontSize, lineHeight)

### Лэйаут

Для сложных компонентов общий лэйакт скелетона будет собирать разработчик и сможет переиспользовать классы и стили готового компонента.

Для более простых кейсов можем добавить 1-мерный компонент лэйаута (либо в строку, либо в колонку). Позже при необходимости сможем проапгрейдить его до 2-мерного.

Примеры:

- Avatar
  ![](http://s.csssr.ru/U07B23NE8/2021-07-19-17-49-51-oankh.jpg)

```tsx
return (
  <Skeleton.Layout direction="horizontal" gap="s">
    <Skeleton.Circle size={24} />
    <Skeleton.Text rows={2} fontSize="s" lineHeight="m" />
  </Skeleton.Layout>
);
```

DSL-версия:

```tsx
// Вариант 1
return <Skeleton.Layout gap="s" layout="circle(24) text(2xS/M)" />;

// Вариант 2
return (
  <Skeleton.Layout
    gap="s"
    direction="horizontal"
    layout={["circle(24)", "text(2xS/M)"]}
  />
);

// Вариант 3
return (
  <Skeleton.Layout
    gap="s"
    direction="horizontal"
    layout={[
      {
        type: "circle",
        size: 24
      },
      {
        type: "text",
        rows: 2,
        fontSize: "s",
        lineHeight: "m"
      }
    ]}
  />
);
```

Во 2 и 3 вариантах получится типизировать опции (во 2 с помощью [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html)). В 1 — нет.

- Image + Text
  ![](http://s.csssr.ru/U07B23NE8/2021-07-19-17-50-58-f7pga.jpg)

```tsx
return (
  <Skeleton.Layout direction="vertical" gap="m">
    <Skeleton.Brick height={200} />
    <Skeleton.Text rows={4} fontSize="m" lineHeight="m" />
  </Skeleton.Layout>
);
```

DSL-версия:

```tsx
// Вариант 1
return <Skeleton.Layout gap="m" layout="brick(100%x200px) \n text(4xM/M)" />;

// Вариант 2
return (
  <Skeleton.Layout
    gap="m"
    direction="vertical"
    layout={(["brick(100%x200px)"], ["text(4xM/M)"])}
  />
);

// Вариант 3
return (
  <Skeleton.Layout
    gap="m"
    direction="vertical"
    layout={[
      {
        type: "brick",
        height: 200
      },
      {
        type: "text",
        rows: 4,
        fontSize: "m",
        lineHeight: "m"
      }
    ]}
  />
);
```

- Heading + Chart
  ![](http://s.csssr.ru/U07B23NE8/2021-07-19-17-53-20-xk2js.jpg)

```tsx
return (
  <Skeleton.Layout direction="vertical" gap="s">
    <Skeleton.Text rows={1} fontSize="m" />
    <Skeleton.Brick height={200} />
  </Skeleton.Layout>
);
```

**Comment by itsmealbina** [comment]
https://consta-uikit-git-feat-skeleton-consta.vercel.app/?path=/story/components-skeleton--skeleton-text-story

Нужно обновить цвета в макете
default: в макете - #DEE4E8, стенд - #ced8de 
dark: макет - #4D525B, стенд - #4b5963 
display: макет - #315581,стенд - #4b6272
На стенде используется переменная для цвета --color-bg-system
