### ISSUE TITLE
Table: экспорт готовых компонент-фильтров во внешний мир

### ISSUE THREAD

**Issue by rim1321** [gazprom-neft/consta-uikit#1102]
Добрый день.
В документации для таблицы с фильтрами описаны готовые кастомные компоненты: TableNumberFilter, TableNumberFilter, TableTextFilter, TableFilterContainer.
Как правильно импортировать эти компоненты в своем проекте?
Сейчас использую:
`import { TableTextFilter } from '@consta/uikit/__internal__/src/components/Table/TextFilter/TableTextFilter';`

**Comment by gizeasy** [comment]
Спасибо за вопрос, проглядели этот момент, сделаем реэкспотр из 
`import { TableTextFilter } from '@consta/Table`

**Comment by gizeasy** [comment]
реализованно
