### ISSUE TITLE
Table: вопросы про filterer

### ISSUE THREAD

**Issue by rim1321** [gazprom-neft/consta-uikit#1103]
Добрый день.
Согласно документации, для фильтрации таблиц используется функция `filterer`. Принимает в себя 2 аргумента (значение ячейки и значение фильтра).
Есть пара вопросов:
1) Если в значении ячейки лежит не строка, а компонент (или еще сложнее - компонент, в нем другой компонент и т.д.). Как правильно брать значение ячейки для сравнения с фильтром? На ум приходит `cellValue.props.children` (если больше вложенных компонент, то и цепочка длиннее). Но кажется это неправильным и легко ломаемым.
2) В документациях примеры где в фильтрах лежат значения из колонки. Что если мы хотим положить туда что-то другое? Например: в колонке у нас месяца (январь, февраль и т.д), а фильтровать хотим по временам года (весна, лето и т.д.). Хотелось бы получать не только cellValue, но и строку целиком (в примере выше была бы скрытая колонка с временами года).

**Comment by gizeasy** [comment]
1) вы можете использовать `renderCell` для представления ячеки, тогда в функцию фильтрации будут падать данные ячеки которые возможно будет отфильтровать
2) попробуйте представлять данные через `renderCell`, тогда в cellValue будет попадать нужное вам значение

**Comment by rim1321** [comment]
Попробовал представлять данные через `renderCell`.
В `cellValue `при фильтрации попадает компонента/текст из `rows`, а не из `renderCell ` из `columns`.
Можете привести работающий пример для второго пункта?
