### ISSUE TITLE
Select, Combobox: Добавить лоадер в выпадающий список

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1106]
Добавить в дизайн, задача на разработку #1105

**Comment by Ilyashis** [comment]
![image](https://user-images.githubusercontent.com/76221581/120758204-f97dc680-c52a-11eb-985b-5e5c1a2777bc.png)
Пример компонентов в состоянии лоадер

**Comment by Ilyashis** [comment]
@kolebayev Привет, жду апрува по UI, и обновлю в kit'е
Для состояния лоадер будет создано свойство - inLoader=true/false

**Comment by Ilyashis** [comment]
В компоненте Combobox, найдены баги.
- Иконки выходят за рамки компонента на 1 px
- Разделяющая линия имеет выступ на 1px
- 
![image](https://user-images.githubusercontent.com/76221581/121013574-6fe02a00-c7b2-11eb-813c-e328a6dfd4ae.png)

**Comment by kolebayev** [comment]
> ![image](https://user-images.githubusercontent.com/76221581/120758204-f97dc680-c52a-11eb-985b-5e5c1a2777bc.png)
> Пример компонентов в состоянии лоадер



> @kolebayev Привет, жду апрува по UI, и обновлю в kit'е
> Для состояния лоадер будет создано свойство - inLoader=true/false

все ок, переноси в kit

**Comment by hell0anna** [comment]
новый вариант лоадера добавлен, старый вариант удален.
Баги с 1px поправлены

**Comment by Lyubavskaya** [comment]
select https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=9701%3A190445
combobox https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=11065%3A140493
