### ISSUE TITLE
Header: двухуровневые пункты меню

### ISSUE THREAD

**Issue by d0ublezer0** [gazprom-neft/consta-uikit#1111]
верстка ломается, если фраза в пункте меню переносится

**Comment by kolebayev** [comment]
@d0ublezer0 Привет! 
Пункты шапки, отвечающие за навигацию в сервисе, должны быть краткими и понятными в пользу скорости взаимодействия. Поэтому они не предполагают длинный текст.

Без контекста задачи могу предложить два варианта доработки на твоей стороне:
1. поработать с формулировками:
- перефразировать
- сократить слова (например корпоративный → корп.)
- использовать аббревиатуры
2. у хэдера есть [свойство className](https://consta-uikit.vercel.app/?path=/docs/components-header--playground#%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0-header), через которое можно добраться до нужного узла в компоненте и доопределить [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)

**Comment by d0ublezer0** [comment]
> @d0ublezer0 есть скрины бага, в каких условиях появился?
Привет! 

<img width="1439" alt="Screenshot at May 12 13-42-37" src="https://user-images.githubusercontent.com/5479787/117962604-1528ef00-b328-11eb-8566-b71389a6a315.png">

Если название пункта меню не помещается в одну строку, то перенос разрывает элемент из-за большой высоты строки. 

В принципе, мы выкрутились переназначением классов, но возникла еще одна проблема - псевдоэлемент, подсвечивающий выделенный пункт меню, отображается по центру родительского, вместо центра текстовой части.

Тут тоже нашли обходной манёвр, через флекс-боксы, но это костыли всё же.

**Comment by kolebayev** [comment]
@d0ublezer0 привет! круто, что нашли решение. По визуалу стоит сократить формулировки, тогда ваш хэдер будет выглядеть аккуратнее.

Если ваша логика продукта позволяет, попробуйте:
Правила проверки → Проверка
Типы таблиц → Таблицы
Шаблоны согласования → Шаблоны
Настройка уведомлений → Уведомления

А мы завели две задачи на дизайн #1149 и разработку #1150, которая исключает этот баг
