### ISSUE TITLE
Combobox: Проблема с тайпскриптом

### ISSUE THREAD

**Issue by dmitriykorsakovnedra** [gazprom-neft/consta-uikit#1116]
При использовании групп не проходит статическая проверка на типизацию. Похоже getGroupOptions ждет на выходе массив групп, а не опций.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/70529732/117958477-b9f4fd80-b323-11eb-86c7-fedcc106b6f2.png)

Вопрос: Почему типизация проходит в сторибуке?
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/70529732/117958890-240da280-b324-11eb-9455-9b7c7ad97137.png)

**Comment by gizeasy** [comment]
пример из сторибука

**Comment by gizeasy** [comment]
type SimpleOption = {
  label: string;
  value: string;
};

type Group = {
  label: string;
  options: SimpleOption[];
};

type Option = SimpleOption | Group;

const items: Option[] = [
  {
    label: 'Чистые цвета',
    options: [
      { label: 'Синий', value: 'а1' },
      { label: 'Зеленый', value: 'a2' },
      { label: 'Красный', value: 'a3' },
    ],
  },
  {
    label: 'Смешанные',
    options: [
      { label: 'Черно-белый', value: 'b1' },
      { label: 'Серо-бурый', value: 'b2' },
    ],
  },
  {
    label: 'Паттерны',
    options: [
      { label: 'В горошек', value: 'c1' },
      { label: 'В полосочку', value: 'c2' },
    ],
  },
];

export const ComboboxExampleGroup = () => {
  return (
    <StoryBookExample className={cnDocsDecorator('Section')}>
      <Combobox
        id="id"
        options={items}
        getOptionLabel={(option) => option.label}
        getGroupOptions={(group: Group) => group.options}
        placeholder="Выберите цвет"
      />
    </StoryBookExample>
  );
};

**Comment by gizeasy** [comment]
```tsx
type SimpleOption = {
  label: string;
  value: string;
};

type Group = {
  label: string;
  options: SimpleOption[];
};

type Option = SimpleOption | Group;

const items: Option[] = [
  {
    label: 'Чистые цвета',
    options: [
      { label: 'Синий', value: 'а1' },
      { label: 'Зеленый', value: 'a2' },
      { label: 'Красный', value: 'a3' },
    ],
  },
  {
    label: 'Смешанные',
    options: [
      { label: 'Черно-белый', value: 'b1' },
      { label: 'Серо-бурый', value: 'b2' },
    ],
  },
  {
    label: 'Паттерны',
    options: [
      { label: 'В горошек', value: 'c1' },
      { label: 'В полосочку', value: 'c2' },
    ],
  },
];

export const ComboboxExampleGroup = () => {
  return (
    <StoryBookExample className={cnDocsDecorator('Section')}>
      <Combobox
        id="id"
        options={items}
        getOptionLabel={(option) => option.label}
        getGroupOptions={(group: Group) => group.options}
        placeholder="Выберите цвет"
      />
    </StoryBookExample>
  );
};
```

**Comment by gizeasy** [comment]
проблема исправиться в этой задаче
https://github.com/gazprom-neft/consta-uikit/issues/1211
