### ISSUE TITLE
Генерации таблицы пропсов 

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#112]
Для генерации таблицы пропсов и нобов можно попробовать заюзать r`eact-docgen-typescript-loader `и `addon-smart-knobs`, но у них есть свои ограничения, которые могут потребовать доработок

**Comment by gizeasy** [comment]
проверить на компоненте из Stories

**Comment by gizeasy** [comment]
Хотеля использовать `Props` из `@storybook/addon-docs/dist/block` но не работает
думаю чтоит подождать сторибук версии 6.0 и попробовать опять

**Comment by fooontic** [comment]
Неактуально.
