### ISSUE TITLE
Tabs: Поддержать адаптивность

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1126]
Сделать это как для горизонтальных, так и для вертикальных табов

**Comment by Lyubavskaya** [comment]
Посмотреть Эра бурение и PPM портал

**Comment by nekitk** [comment]
На обсуждении решили пока делать только для горизонтальных.

**Comment by itsmealbina** [comment]
https://consta-uikit-git-dev-consta.vercel.app/?path=/story/components-tabs--playground
1. Не переключается таб при длинном названии на узком экране
Скринкаст с реального устройства (android): http://s.csssr.ru/UFALX8YMV/tabs_mobile_chrome.mp4
2. На ios не видно кнопки для дропдауна, отображается только 1 таб из 4
Скрин из browserstack: http://s.csssr.ru/UFALX8YMV/20210818_105115.jpg
Скрин с реального устройства: http://s.csssr.ru/UFALX8YMV/tabs_ios_chrome.png
