### ISSUE TITLE
docs: Ревью примеров в документации 

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1132]
Проблема: 
Бывает, что не хватает типов для пропсов.
Не хватает примеров с кодом. Сейчас приходится периодически смотреть в репозиторий. 
"Бывает не соответствие того, как реализовано и как описано. Не хватает use кейсов. В док-ии может быть указано, а в самом интерфейсе этого нет."

Что нужно сделать: 
Ревью - просмотреть код примеров в документации и обновить, если что-то не так. 
Посмотреть все примеры и выявить примеры без примера кода.
Должны быть представлены примеры кода, которые можно копировать, вставлять на проект. 

Результатом задачи должны быть задачки на добавление/корректировку примеров кода для каждого компонента.

**Comment by Lyubavskaya** [comment]
https://github.com/gazprom-neft/consta-uikit/issues/1144

**Comment by gizeasy** [comment]
результат задачи - список того что нужно поправить и созданные задачки

**Comment by N1MBER** [comment]
### _**Attach**_
Type mistake: в коде withAction, в песочнице withButtonAction, в документации данный props не прописан_**Attach**_
### _**Breadcrumbs**_
В документации не прописано что maxCount по дефолту имеет значение 0
### _**Calendar**_
Возможно стоит изменить тип для events, на CalendarEvents: {date: Date, label?: string}[], чтобы при наведении на конкретную обозначенную дату выползала подсказка, что это за день / какое назначено мероприятие.
### _**CheckboxGroup**_
В примерах вроде как перепутаны местами значения, где должно стоять direction='row' стоит direction='column' и наоборот
### _**Switch**_
На мой взгляд стоит добавить пример использования параметра required, так как не совсем понятно с первого взгляда, как это должно работать.
### _**Tooltip**_
Стоит вынести примеры позиционирование примеров вверх, так как результат и код находятся в двух разных блоках и пользователю может быть не понятно, что к чему относится. 
### _**SnackBar**_
Стоит представить свойства немного в ином виде, так как мне как человеку, который первый раз смотрел на данную страницу было не понятно что за что отвечает, по хорошему все перечисления вынести в одну строчку.




В целом пожелание к документации, чтобы когда мы выбираем новый компонент нас перемещало в начало страницы.
