### ISSUE TITLE
Table: Дополнить документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1140]
1. Добавить примеры.
2. Фильтрация в таблицах описана плохо, люди разбираются долго.
3. Проверить, поправить моменты по импорту и сортировке в таблице. Дополнить описание при необходимости.

**Comment by Lyubavskaya** [comment]
+ добавить в доку изменения, которые были сделаны в рамках ишью #1730

**Comment by AntonS86** [comment]
документация по кастомным фильтрам, как подписаться на изменения, как установить новые значения, если денные из вне
