### ISSUE TITLE
Text: Добавить автоматический ellipsis 

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1143]
**Описание фичи или улучшения**
Автоматический ellipsis (троеточие, если много текста) - пропсом у компонента Text 
+ Просмотреть, в каких компонентах это нужно. У каждого такого комп-та добавить свойство.

**Comment by gizeasy** [comment]
то есть должен быть модификатор `ellipsis: boolean` по которому текст сворачивался в три точки если не входит в одну строку

**Comment by Lyubavskaya** [comment]
2 свойства:

**Comment by AntonS86** [comment]
может быть назвать свойство `truncate`?
