### ISSUE TITLE
components: Ревью типов

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1144]
Типизация не всегда понятно написана. Зачастую приходится методом тыка проверять, что нужно передать в компонент (что он ожидает)  (ФИТ).

**Comment by Lyubavskaya** [comment]
https://github.com/gazprom-neft/consta-uikit/issues/1132

**Comment by gizeasy** [comment]
результатом задачи ссылки на файл где что-то непонятно
и может предложения по улучшению

**Comment by N1MBER** [comment]
### _**Attach**_
Props fileExtension имеет тип string, возможно имеет смысл завести enum допустимых типов расширений и типизировать  fileExtension через него, в таком случае ide будет подсказывать разработчикам доступные значения.
### _**Badge**_
На мой взгляд имеет смысл добавить свойство iconPosition: ['left', 'right'] (как в Collapse), так как может быть такое что необходимо отобразить иконку справа.
### _**DragNDropField**_
Возможно имеет смысл добавить кастовый текст ошибок и ивент который будет возвращать тип ошибки и причину ее возникновения.
### _**File**_
Тоже замечание что и в Attach, так как Attach использует File, стоит в нем создать кастомный тип для типизации расширений.
### _**ProgressSpin**_
Стоит добавить еще хотя бы один размер: xl (а лучше еще 2xl), так как если разработчик делает сайт и хочет добавить спин лоудер на загрузку контента, нынешней размерной сетки ему может не хватить.

**Comment by gizeasy** [comment]
### _**Attach**_
давай сделаем перечисления но и `string` тоже оставляем
### _**Badge**_
не делаем, ограничения дизайна
### _**File**_
давай сделаем перечисления но и `string` тоже оставляем
### _** ProgressSpin**_
Создай отдельно задачку на это, поставь на @kolebayev и @gizeasy , обсудим
