### ISSUE TITLE
header: добавить сворачивание пунктов меню под кнопку

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1149]
**Описание фичи или улучшения**
Добавить возможность прятать часть пунктов навигационного меню в хэдере под кнопку

**Почему улучшение или фича необходима?**
Решим проблему багов и автопереноса строк, когда в меню шапки используют длинные формулировки или самих пунктов меню много что они не влезают в свободную ширину

**Реализация предложения**
Дополнить компонент Header в фигме, либо написать рекомендации

**Дополнительная информация**
Создано из #1111 
Задача на разработку #1150

**Comment by kolebayev** [comment]
пример решения
![изображение](https://user-images.githubusercontent.com/24884175/118123566-23950a80-b3fd-11eb-9731-7463f7f5fea1.png)

**Comment by Lyubavskaya** [comment]
Будет реализовано в новом хедере
