### ISSUE TITLE
header: добавить сворачивание пунктов меню под кнопку

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1150]
**Описание фичи или улучшения**
Добавить возможность прятать часть пунктов навигационного меню в хэдере под кнопку

**Почему улучшение или фича необходима?**
Решим проблему багов и автопереноса строк, когда в меню шапки используют длинные формулировки или самих пунктов меню много что они не влезают в свободную ширину

**Реализация предложения**
Проапдейтить модуль `HeaderMenu` по предложенному дизайну из #1149 

**Дополнительная информация**
Создано из #1111

**Comment by Lyubavskaya** [comment]
Будет реализовано в новом хедере
