### ISSUE TITLE
landing: Доработать условия заглушки на обновления браузера

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1156]
решения:
1) нужно указать для всях браузеров условия
```
Chrome: 'Chrome',
  Firefox: "Firefox",
  Opera: "Opera",
  Yandex: "Yandex",
  Safari: "Safari",
  InternetExplorer: "Internet Explorer",
  Edge: "Edge",
  Chromium: "Chromium",
  Ie: 'IE',
  MobileSafari: "Mobile Safari",
  EdgeChromium: "Edge Chromium",
  MIUI: "MIUI Browser",
  SamsungBrowser: 'Samsung Browser'
```

2)  скорее всего лучше указать не разрешенный браузеры а запрещенные, в начале запретим только IE
если будут запросы что чтото где-то не работает будем запрещать определенный версии браузеров.

**Comment by Lyubavskaya** [comment]
Фраза для сообщения посетителям из браузеров IE:

Ваш браузер не поддерживается.
Воспользуйтесь браузерами на базе Chromium.
