### ISSUE TITLE
Table: Отсутствует поддержка ref

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1159]
**Описание фичи или улучшения**
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

**Почему улучшение или фича необходима?**
Хочу работать с таблицей программно, но не могу.

**Comment by Lyubavskaya** [comment]
@andreynovikov  Привет! Ссылку какого элемента таблицы вы хотите получить, рута?

**Comment by andreynovikov** [comment]
Да.
