### ISSUE TITLE
Table: кастомный callback для getTagLabel у фильтров

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1190]
**Описание фичи или улучшения**

Сделал в таблице кастомный фильтр по диапазону дат, всё в целом неплохо, кроме отображения текущего значения фильтра в `TableSelectedOptionsList`:
https://github.com/gazprom-neft/consta-uikit/blob/639818524e8dea91b26aad2dc6c66fef637519b9/src/components/Table/SelectedOptionsList/TableSelectedOptionsList.tsx#L30

В данный момент это выглядит как:
> Диапазон дат: от Wed May 12 2021 00:00:00 GMT+0300 (Moscow Standard Time) до Fri May 14 2021 00:00:00 GMT+0300 (Moscow Standard Time)

Хотелось бы иметь контроль над представлением этой строки, тем более для совсем нестандартных фильтров.

**Comment by andreynovikov** [comment]
Добавлю картинку:

![2](https://user-images.githubusercontent.com/2943625/119137999-12c24580-ba4a-11eb-92f6-0c8632f887ac.png)

**Comment by Lyubavskaya** [comment]
либо строка, либо функция, в которую падает значение фильтра
