### ISSUE TITLE
Calendar: неправильное отображение начального значения диапазона

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1192]
**Описание бага**

Имею:
```
<Calendar
  type="date-range"
  view="slider"
  value={this.state.range}
  onChange={({value}) => this.setState({ range: value })}
  maxDate={new Date()}
/>
```

Если при отображении календаря указанный диапазон находится в предыдущем месяце, то календарь всё равно изначально отображает текущий месяц, а не месяц с указанным диапазоном.

**Версия Consta Kit**
1.11.14

**Comment by gizeasy** [comment]
попробуй воспользоваться `currentVisibleDate`

**Comment by gizeasy** [comment]
@kolebayev как думаешь стоит ли задавать по умолчанию месяц с которого открывается календарь?
сдесь  https://github.com/gazprom-neft/consta-uikit/issues/1191 задача про это же только завязаться надо будет на `minDate` и `maxDate`

@andreynovikov как думаешь норм логика? При открытии календаря, будет открываться не текущий месяц  а выбранное значение(либо начало диапазона), если его нет то орентируемся `minDate` и `maxDate` если текущая дата входит в диапазон то ставим ее, если диапазан раньше чем текущая дата то ставим `maxDate` если позже то `minDate`

Напомню что сейчас есть `currentVisibleDate` c помощью которого можно уставить дату с которой откроется календарь

**Comment by gizeasy** [comment]
@andreynovikov @kolebayev думаю что стоит переименовать `currentVisibleDate` на `startVisibleDate`, что думаете?
