### ISSUE TITLE
Calendar: выбор диапазона из одной даты

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1195]
**Описание фичи или улучшения**

Иногда необходимо выбрать диапазон дат из одной даты, т.е. с 12 мая по 12 мая.

**Почему улучшение или фича необходима?**

Мы работаем с большим массивом данных, и хоть обычно данные фильтруются по широкому диапазону, иногда их так много, что необходимо сузить диапазон до одного дня.

**Реализация предложения**

Как сейчас сделано в компоненте:
1. Нажимаешь на одну дату - устанавливается "от"
2. Нажимаешь на другую дату - устанавливается "до"
3. Снова нажимаешь на некую дату - устанавливается "от"
4. Нажимаешь на **ту же** дату - ничего не происходит
5. Нажимаешь на **другую** дату - устанавливается "до"

Как это обычно реализовано в других библиотеках:
1. Нажимаешь на одну дату - устанавливается "от"
2. Нажимаешь на другую дату - устанавливается "до"
3. Снова нажимаешь на некую дату - устанавливается "от"
4. Нажимаешь на **ту же** дату - устанавливается "до"
5. Нажимаешь на **другую** дату - устанавливается "от"

Т.е. нажатия всегда парные - без пропусков: "от", "до", "от", "до", "от", "до".

**Comment by gizeasy** [comment]
спасибо, добавим эту возможность

**Comment by gizeasy** [comment]
Будет реализовано в рамках #1166
