### ISSUE TITLE
Selects: атрибут disabled для элементов (options) 

### ISSUE THREAD

**Issue by shark02807** [gazprom-neft/consta-uikit#1196]
Описание фичи или улучшения

Иногда необходимо отобразить некоторые элементы недоступными (неактивными)

Почему улучшение или фича необходима?

Мы работаем с связанными фильтрами, и есть случаи, когда, при выбранном значении одного фильтра, становятся недоступными некоторые значения другого фильтра, отображаемые через BasicSelect

Реализация предложения

Расширить тип элементов Options, добавив в него параметр disabled

**Comment by gizeasy** [comment]
BasicSelect, combobox, multicombobox, userSelect
