### ISSUE TITLE
Select, Combobox: добавить возможность прокидывать компоненты в option

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1201]
**Описание фичи или улучшения**

Подготовить дизайн-требования фиче: возможность добавления в option выпадающего списка не только текст, но и текст + иконка/бейдж

**Почему улучшение или фича необходима?**
Для увеличения информативности компонента

**Реализация предложения**
В фигме

**Comment by hell0anna** [comment]
select https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=9701%3A190445
combobox https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=11065%3A140493
