### ISSUE TITLE
Tabs: Добавить горизонтальную прокрутку табов

### ISSUE THREAD

**Issue by AlienCode123** [gazprom-neft/consta-uikit#1203]
Компонент [**Tabs**](https://consta-uikit.vercel.app/?path=/tabs/components-tabs--playground)

Хочется видеть в компоненте Tabs прокрутку для его вкладок (шапок), выходящих за границу родителя, с двумя кнопками - назад и вперёд (влево, вправо) по краям соответственно, для показа скрытых вкладок. 
При этом надо отключить перенос вкладок на новые строки.

**ДОПОЛНИТЕЛЬНЫЕ ВОЗМОЖНОСТИ**

**СКРЫТИЕ ВКЛАДОК ЗА ГРАНИЦЕЙ КОНТЕЙНЕРА И ОТОБРАЖЕНИЕ КНОПОК ПЕРЕМЕЩЕНИЯ**
- Если ширина всех табов не достигает границы родителя, то кнопки навигации не отображаются. (Изображение 1)
- Если ширина всех табов достигает границы родителя, то вместо переноса скрывать выходящие за границы родителя вкладки и отображать кнопки для навигации по бокам табов. (Изображение 2)

**РАБОТА КНОПОК ПЕРЕМЕЩЕНИЯ**
- По нажатию на кнопку Влево или Вправо табы должны прокручиваться с видимой линейной анимацией:
  - Если от начальной позиции доступно >= 80% перемещения, то на 80%
  - Если меньше, то на на всю доступную ширину до края.
    
- Если начало/конец контейнера вкладов прилегает к кнопке навигации, то запрещаем её до момента, пока контейнер перестанет прилегать к кнопке. (Изображение 3)

**ДИЗАЙН**
Вкладки с кнопками должны быть реализованы приблизительно к приложенному дизайну.

**ИЗОБРАЖЕНИЯ**
![Изображение 1](https://user-images.githubusercontent.com/81331140/119453095-bd36b300-bd3f-11eb-93bd-3abc8e257e16.png)
![Изображение 2](https://user-images.githubusercontent.com/81331140/119453100-bdcf4980-bd3f-11eb-9bed-226c3871265b.png)
![Изображение 3](https://user-images.githubusercontent.com/81331140/119453092-bc058600-bd3f-11eb-9f09-9e55b95c5847.png)

**Comment by Lyubavskaya** [comment]
Вместе с https://github.com/gazprom-neft/consta-uikit/issues/1125

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=12745%3A116509

В примерах показан пример адаптивной версии в двух версиях, а так же версия когда появляются стрелки для прокрутки
