### ISSUE TITLE
Calendar: Как стилизовать отдельный день?

### ISSUE THREAD

**Issue by rim1321** [gazprom-neft/consta-uikit#1207]
Добрый день.
Как стилизовать отдельный день?
Например: точка о митинге под днем
![image](https://user-images.githubusercontent.com/13187096/119609106-75339100-be10-11eb-8976-33789d61d08b.png)

**Comment by gizeasy** [comment]
могу закрыть issue?

**Comment by rim1321** [comment]
да - под мои задачи подходит, спасибо.
я почему-то предполагал что будет какая-та кастомизация плиток-дней
