### ISSUE TITLE
Breadcrumbs: Добавить выпадающее меню 

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1209]
выпадающее меню должно появляться если хлебный крошки не помещаются в родителя
выпадающее меню для иерархии

**Comment by Ilyashis** [comment]
Изменения по компоненту:
1) Обновлен компонент «button» на «button: variants» 
2) Создано состояние компонента «button», сворачивание иерархии — и привязана к свойству more=True/False
3) Показано примеры использования компонента «Breadcrumbs»

**Comment by Ilyashis** [comment]
4. Написан гайд по использованию компонента для UI кита.
