### ISSUE TITLE
Selects: рефакторинг

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1211]
- [x] вынести группы отдельно от элементов списка https://github.com/gazprom-neft/consta-uikit/issues/1116
- [x] https://github.com/gazprom-neft/consta-uikit/issues/1038
- [x] https://github.com/gazprom-neft/consta-uikit/issues/1021
- [x] #1134
- [x] #1224
- [ ] #387
- [x] Апи компонентов должно быть выполнено таким образом что есть возможность указать любой тип `Item` и `Group` но по умолчанию должны иметь определенный тип с готовыми дефолтными гетерами
- [x] Рендер функции опций

**Comment by Lyubavskaya** [comment]
Заодно вот эти ишью:
https://github.com/gazprom-neft/consta-uikit/issues/1134
https://github.com/gazprom-neft/consta-uikit/issues/1224
https://github.com/gazprom-neft/consta-uikit/issues/387

**Comment by Lyubavskaya** [comment]
еще: https://github.com/gazprom-neft/consta-uikit/issues/1240
