### ISSUE TITLE
Bullet: Финальная доработка

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1212]
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3763%3A0

_Originally posted by @schurf-des in https://github.com/gazprom-neft/consta-uikit/issues/1179#issuecomment-848697715_

**Comment by Lyubavskaya** [comment]
https://github.com/gazprom-neft/consta-charts/pull/7
