### ISSUE TITLE
Scatter: Финальная доработка

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1213]
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3743%3A0

_Originally posted by @schurf-des in https://github.com/gazprom-neft/consta-uikit/issues/1180#issuecomment-848697474_

**Comment by Lyubavskaya** [comment]
https://github.com/gazprom-neft/consta-charts/pull/7
