### ISSUE TITLE
Tabs: Возможность отображать Badge, иконку

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1229]
По итогам опроса: "Добавьте табам возможность отображать Badge. Например, есть задача выводить в табе цифру с количеством элементов ожидаемых на странице."

**Comment by kolebayev** [comment]
иконка есть, полевому краю. надо добавить бейдж справа и слева

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=12745%3A116509

Обновлен компонент tabs для трех тем
