### ISSUE TITLE
Calendar: февраль в двухмесячном отображении

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#1234]
**Описание бага**

Если февраль начинается с понедельника, то последний ряд дней пустой, а должен по аналогии содержать начальные дни марта.

![](https://user-images.githubusercontent.com/2943625/120162385-fd46db80-c200-11eb-821c-0f756446b00a.png)

**Версия Consta Kit**
1.11.14

**Comment by Lyubavskaya** [comment]
Это общепринятая логика поведения такого компонента.
