### ISSUE TITLE
Совместимость с фреймворком Next.js

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1239]
Столкнулись с проблемой совместимости ui-кита ГПН с фреймворком Next.js.
На GitHub она была описана еще год назад, но решения не получила. https://github.com/gazprom-neft/consta-uikit/issues/155

**Comment by Lyubavskaya** [comment]
Удалось решить данную проблему
Необходимо установить npm пакеты @zeit/next-css, @zeit/next-sass, next-transpile-modules, next-compose-plugins
Далее в next.config.js
const withPlugins = require('next-compose-plugins');
const withTMFactory = require('next-transpile-modules');
const withCss = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const plugins = [withTMFactory(['@consta']), withCss, withSass];
module.exports = withPlugins(plugins, config);

в .babelrc.js
module.exports = {
  presets: [['next/babel']],
  plugins: [['styled-components', { ssr: true }]],
};

Плагины @zeit/next-css, @zeit/next-sass официально считаются deprecated, т.к. next с версии 9.5.4 поддерживает импорт стилей, но т.к. импорт стилей происходит в  node_modules и стили не являются css modules, next видит в этом проблему.
Поэтому можно или руками сконфигурировать вебпак на то, чтобы он при компиляции пакета все css импортировал как модули, или поставлять пакет со стилями в виде css модулей, тогда будет работать "из коробки"

**Comment by wolfcreative** [comment]
Оставлю потомкам.
Начиная с версии 13 можно использовать встроенный `transpilePackages` в next.config.js

Пример:
const nextConfig = {
	reactStrictMode: true,
	experimental: {
		appDir: true,
	},
	transpilePackages: ['@consta'], **<- тут перечисляем нужное**
}

**Comment by UsVfxArtia** [comment]
> Оставлю потомкам. Начиная с версии 13 можно использовать встроенный `transpilePackages` в next.config.js
> 
> Пример: const nextConfig = { reactStrictMode: true, experimental: { appDir: true, }, transpilePackages: ['@consta'], **_<- тут перечисляем нужное_** }

Окей, но я верно понимаю что дальше нужно в layout.tsx написать так?

```
"use client";
import { Theme, presetGpnDefault } from "@consta/uikit/Theme";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <Theme preset={presetGpnDefault}>{children}</Theme>
      </body>
    </html>
  );
}
```
И у меня вопрос
Без "use client" выдаёт ошибку, как тогда использовать?
```
error - ./node_modules/@consta/uikit/__internal__/src/components/Theme/Theme.js
ReactServerComponentsError:

You're importing a component that needs createContext. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
```

И еще, при попытке поместить <Theme></Theme> на самый верх, чтобы стили применились ко всему html и body не работает как надо, на сайте через 5 секунд перестают отображаться данные.

**Comment by wolfcreative** [comment]
Всё проще. В _app.tsx (мы же речь о NextJS ведём) чуть-чуть дописываем поверх стандартного подключении темы и получится примерно так:

`import type { AppProps } from 'next/app'
import { Theme, presetGpnDefault } from '@consta/uikit/Theme'

export default function App({ Component, pageProps }: AppProps) {
	return (
		<Theme preset={presetGpnDefault}>
			<Component {...pageProps} />
		</Theme>
	)
}
`

**Comment by alekseykurylev** [comment]
А как использовать Link в компонентах consta???

**Comment by wolfcreative** [comment]
@alekseykurylev если не ошибаюсь, Link работал как обычно.
Мы в проекте ушли на UIKit, с CONSTA+Next.js много ненужных компромиссов приходилось принимать.

**Comment by alekseykurylev** [comment]
@wolfcreative вы имеете в виду getuikit.com?

**Comment by wolfcreative** [comment]
@alekseykurylev да. Вам посоветую TailwindCSS или что-то похожее. У него документация и примеры на все случаи жизни.

**Comment by alekseykurylev** [comment]
@wolfcreative, подскажите как подрубали uikit в nextjs
