### ISSUE TITLE
storybook: Добавить плагин для отображения цветов

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1246]
**Описание фичи или улучшения**
Мы сами делали разметку для превью цветов, можно это автоматизировать

**Почему улучшение или фича необходима?**
Легче поддерживать

**Реализация предложения**
https://github.com/UX-and-I/storybook-design-token

**Comment by Lyubavskaya** [comment]
Будем делать на новом портале Consta
