### ISSUE TITLE
Theme: ресерч размеров --line-height-text

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1258]
сейчас у `Text` есть проблема, при `line-height: var(--line-height-text-2xs)` стоит значение `1em`, в этом случае если накинуть `overflow: hidden`, то буквы висящие в низ (g,y,j) обрезаются. 
Довольно часто нам нужно скрывать под точки текст, а он еще и обрезается с низу((

**Comment by hell0anna** [comment]
переменная line-height-2xs была изменена на 1.1em
https://www.figma.com/file/4FOymgclcGF3Fm2M9ZeNUk/Consta-Default-Typography?node-id=62%3A0
