### ISSUE TITLE
Table: Добавление новой строки

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1275]

**Comment by Ilyashis** [comment]
https://www.figma.com/file/Wso1cGnXG6TbeBZkKklIH0/Draft.Table?node-id=0%3A1

**Comment by Ilyashis** [comment]
UP
@Lyubavskaya https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=1586%3A5021
