### ISSUE TITLE
TableFilterTooltip: убрать закрытие тултипа при использовании BasicSelect в фильтре

### ISSUE THREAD

**Issue by AlexLevus** [gazprom-neft/consta-uikit#1283]
**Описание бага**
При использовании компонента BasicSelect в кастомном табличном фильтре закрывается компонент TableFilterTooltip. Значение в BasicSelect также не устанавливается. 

**Версия Consta Kit**
1.12.3

**Параметры софта на компьютере:**

- ОС: Windows 10 x64
- Браузер и его версия: Google Chrome 91.0.4472.77

**Comment by gizeasy** [comment]
@AlexLevus можешь приложить кусок когда, где описываешь параметры компонента и приложить видео как оно работает. Чтоб понимать что конкретно пытаешься сделать

**Comment by AlexLevus** [comment]
@gizeasy  
Видео: https://disk.yandex.ru/i/T9hB7a8Zx3uFtw
Кусок кода:
```
  const filterBody = (
    <div className="filter">
      <BasicSelect
        id="id"
        className="filter__type-select"
        value={condition}
        size="s"
        options={filterConditionItems}
        getOptionLabel={(item) => item.label}
        onChange={onMethodChange}
      />
      {condition?.value !== TextFilterConditionType.None && (
        <TextField
          id="id"
          width="full"
          size="s"
          value={equalsToValue}
          onChange={({ value }) => onValueChange(value)}
        />
      )}
    </div>
  );

  return isTableFilter ? (
    <TableFilterContainer
      onCancel={onCancel}
      onConfirm={confirmHandler}
      confirmButtonLabel="Показать"
      cancelButtonLabel="Сбросить"
    >
      {filterBody}
    </TableFilterContainer>
  ) : (
    filterBody
  );
```

**Comment by gizeasy** [comment]
@AlexLevus спасибо, понял в чем проблема. Пошел исправлять)))

**Comment by AlexLevus** [comment]
@gizeasy Спасибо!
Еще другой вопрос сразу вдогонку) Как лучше всего сделать контекстное меню для добавления строк/столбцов в таблице?
В react-data-grid для этого есть пропс contextMenu, но в таблице Consta ничего подобного не нашел. Есть какие-нибудь идеи? И планируется ли добавление подобной возможности?

**Comment by gizeasy** [comment]
> @gizeasy Спасибо!
> Еще другой вопрос сразу вдогонку) Как лучше всего сделать контекстное меню для добавления строк/столбцов в таблице?
> В react-data-grid для этого есть пропс contextMenu, но в таблице Consta ничего подобного не нашел. Есть какие-нибудь идеи? И планируется ли добавление подобной возможности?

Тут скорее всего виднее тому кто будет экспериментировать. Если нужно вставлять элемент в конкретное место(между конкретными столбцами или строками) то кажется ни как. Если надо вставлять либо с низу либо с верху, без учёта позиции, то в целом можно по клику правой клавишей по всей таблице вызывать контекстное меню, с позицией по которой был клик.
