### ISSUE TITLE
Sidebar: Добавить модификаторы width и height

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1292]

**Comment by gizeasy** [comment]
сейчас тянется во всю ширину контента, мы хотим свои модификаторы ширины ровно для того чтобы стандартизировать ширину?

**Comment by gizeasy** [comment]
@kolebayev можешьподсказать какие возможные ширины можно прокидывать?

**Comment by kolebayev** [comment]
@gizeasy давайте по дефолту .25vw

**Comment by gizeasy** [comment]
2 модификатора `width`, `height`, в типах зависят от `position`
значения:
s: 260px
m: 320px
l: 480px
oneQuarter: 25vh/vw
threeQuarters: 75vh/vw
half: 50vh/vw
oneThird: 33.33vh/vw
twoThirds: 66.66vh/vw
full: 100 vh/vw

все максимально должны тянуться до 100vh/vw
