### ISSUE TITLE
Tabs: Добавить горизонтальную прокрутку табов

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1305]
Дизайн: https://github.com/gazprom-neft/consta-uikit/issues/1203

**Comment by nekitk** [comment]
На обсуждении решили пока делать только для горизонтальных.

**Comment by itsmealbina** [comment]
https://consta-uikit-git-dev-consta.vercel.app/?path=/story/components-tabs--playground
