### ISSUE TITLE
MultiCombobox/S/Default/Filled: неправильно стоят констрейны

### ISSUE THREAD

**Issue by Ptitzin** [gazprom-neft/consta-uikit#1307]
**Описание бага**
При вытягивании бокса размера S крестик остается вверху, а не по центру
В размере L все хорошо
![image](https://user-images.githubusercontent.com/78861041/123289131-d5554a00-d518-11eb-85d4-04e9dd6b86cf.png)

**Как воспроизвести баг** (опционально)  
берем MultiCombobox/S/Default/Filled растягиваем вниз

**Comment by Ilyashis** [comment]
Исправлено
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=367%3A0
