### ISSUE TITLE
Table: иконка разворачивания строки не в первой колонке

### ISSUE THREAD

**Issue by rim1321** [gazprom-neft/consta-uikit#1312]
Добрый день.

Правильно понимаю что иконки для разворачивания строк всегда рисуются в первой колонке?
Есть необходимость реализовать это во второй колонке (в первой узкой колонке будут статусы).
Можно ли это реализовать сейчас и как?
Если нет - планируются ли в ближайшем будущем такие наработки?

**Comment by gizeasy** [comment]
Взяли в работу, на выявление проблемы
