### ISSUE TITLE
Avatar: Скорректировать отступы в XS размере

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1323]
Откорректируйте отступы компонента Avatar при XS размерах  https://yadi.sk/i/XhuY9h1lqU64iw

**Comment by Ilyashis** [comment]
Исправлено
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=56%3A30966
