### ISSUE TITLE
telegram-bot: Публикация обновлений графиков в телеграм-канале

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1332]
Для Consta Charts

**Comment by gizeasy** [comment]
Парсинг текста поняменять таким образом чтобы возможнобыло описание включать в 
 ```
---
Описание
---
```

**Comment by gizeasy** [comment]
И также на вский случай предусматреть защиту от дурака, чтоб ни какой другой контенот релиза не смог сломать бота
