### ISSUE TITLE
Избавиться от дублирования иконок

### ISSUE THREAD

**Issue by nekitk** [gazprom-neft/consta-uikit#134]
Завёл по мотивам обсуждения в пр-е про добавление новых иконок:
https://github.com/gpn-prototypes/ui-kit/pull/132#discussion_r425633843

Насколько понимаю, из-за особенностей текущего механизма сборки иконок получается, что в проекте одновременно лежат и svg-иконки, и их же представление в виде tsx-компонента. При этом tsx-компонент иконки не импортит svg, а дублирует её.

Нужно доработать сборку иконок таким образом, чтобы дублирования не было в репозитории. Один из вариантов — использовать `babel-plugin-named-asset-import`, который позволит импортить svg и использовать сразу как Реакт-компонент, тогда от tsx-обёрток можно будет избавиться и оставить только svg.

**Comment by gizeasy** [comment]
Сейчас `babel-plugin-named-asset-import` сложно будет заюзать так как сборка кастомная
