### ISSUE TITLE
Drag'n'dropField: Поправить замечания по итогам тестирования

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1359]
1. Отличается border-radius для всей области dragndrop
Стенд - 4px, макет - 8px http://s.csssr.ru/UFALX8YMV/20210721_141018.jpg
2. Не меняется текст и цвет фона при перетаскивании одного/нескольких файлов
Скрин со стенда http://s.csssr.ru/UFALX8YMV/20210720_185800.jpg, макет https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=34445%3A0

**Comment by nekitk** [comment]
1. С Ильёй решили оставить для радиуса общую переменную, которая 4px
2. Поправлю

**Comment by itsmealbina** [comment]
https://consta-uikit-git-fix-dnd-test-consta.vercel.app/?path=/story/components-dragndropfield--playground
