### ISSUE TITLE
Skeleton: Обновить цвета в макете

### ISSUE THREAD

**Issue by itsmealbina** [gazprom-neft/consta-uikit#1379]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=25097%3A0

Темы:
* default: в макете - #DEE4E8, стенд - #ced8de
* dark: макет - #4D525B, стенд - #4b5963
* display: макет - #315581,стенд - #4b6272

На стенде используется переменная для цвета --color-bg-system

**Comment by Lyubavskaya** [comment]
Понять, где правильно, в макете или в коде и поправить

**Comment by kolebayev** [comment]
#882 после выполнения закрыть и эту

**Comment by hell0anna** [comment]
цвета в фигме поправлены 
на стенде сейчас тоже актуальные цвета, но лучше перепроверить

**Comment by hell0anna** [comment]
актуальные цвета:
default:  #DEE4E8
dark:  #4D525B
display:  #315581
