### ISSUE TITLE
дизайн блока BasicSelect, Combobox и `multiCombobox

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#143]

**Comment by fooontic** [comment]
### Мысли по поводу вариаций селекта. 

**SimpleSelect**
- Выбор одного элемента списка.
- Нет плейсхолдера, но есть дефолтное значение.

**SelectWithSearch**
- Выбор одного элемента списка
- Есть плейсхолдер. 
- Может быть предвыбранное значение.
- Есть поиск по списку. Походу набора список фильтруется по введённому значению.
- Опциональная опция «Добавить своё значение». 

**MultiSelect**
- Выбор нескольких элементов списка.
- Есть плейсхолдер.
- Может быть предвыбранное значение.
- Есть поиск по списку. Походу набора список фильтруется по введённому значению. 
- Поле ввода сдвигается каждый раз походу добавления элементов. 
- Мультристрочный. Будет ограничение по высоте (пока не определено).
- Опциональная опция «Добавить своё значение».

**Comment by tsvetta** [comment]
Созвон с Вадимом и Олегом

Старый селект, слишком жирный, сложно поддерживать

https://github.com/gpn-prototypes/ui-kit/blob/master/src/components/Select/index.tsx

В миро будет блоксхема с поведением компонента в зависимости от разных условий

У нас точно будет простой тупейший селект, где будет просто выбор одного пункта из списка значений, не будет плейсхолдера

Хотят целиком и полностью свое. Олег предлагает фреймворк для селектов, есть работа с клавиатуры, нет дизайна: https://www.downshift-js.com/ 
Поле ввода селекта должно быть основано на TextField из ДС.

Выпадашка должна быть отдельным компонентом.

Мобильную версию не закладываем пока.

Попробовать использовать нативные теги select и options, скрывая их.


Варианты селектов:

- мультиселект с деревом/без дерева

**Comment by fooontic** [comment]
Ссылка на блоксхему. https://miro.com/app/board/o9J_kya0n8I=/?moveToWidget=3074457348145252676&cot=13 Будет скорее всего дополняться.

**Comment by fooontic** [comment]
Обсудили внимательно с @Miocene. Решили, что вариант с деревом излишний. Делать его не будем. Завтра ещё с командой это обсудим и точно напишу.

**Comment by fooontic** [comment]
Макет https://www.figma.com/file/FLCwrJTceo6xB9VInayasa/UI-Kit-Default?node-id=5464%3A6743

**Comment by fooontic** [comment]
У нас весь UI-kit в Фигме переехал в другой общедоступный репозиторий и заодно мы его теперь оформляем сразу во всех трёх темах  разом, а не как раньше. 

Новый макеты теперь здесь. На данным момент получилось разбить селект на такое количество компонентов:
1. SimpleSelect https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/GPN-UI-Kit?node-id=366%3A0
2. Combobox https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/GPN-UI-Kit?node-id=366%3A1392
3. MultiCombobox https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/GPN-UI-Kit?node-id=367%3A0
4. UserSelect (он пока не доделан во всех темах и не расписаны различные кейсы, но общее представление есть) https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/GPN-UI-Kit?node-id=367%3A5636

В каждом компоненте описаны узкие кейсы использования, возможно, какие-то не не учёл, если надо будет — буду по возможности дополнять.

**Comment by fooontic** [comment]
^ @tsvetta

**Comment by fooontic** [comment]
Для компонента MultiCombobox предварительно нужно будет сделать компонент Tag https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/GPN-UI-Kit?node-id=123%3A0 надо будет это учесть и запланировать разработку его параллельно или заранее.
