### ISSUE TITLE
Tabs: Неправильно реагирует на ререндер

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1439]
Компонент Tabs неправильно реагирует на ререндер. В случае, если не мемоизировать массив, передаваемый в items (массив находится внутри компоненты), то пропадает подчёркивание активного таба.

**Comment by nekitk** [comment]
Не баг, т.к. активность компонента вычисляется по переданному пропсу `value`. Если `value` нет в переданных `items`, то это значит, что ни один таб не выбран. Аналогично работают и другие компоненты, использующие выбор айтема: например, в ChoiceGroup будет слетать выбранный айтем, если постоянно передавать ему новый массив `items`.

Раньше в табах могло казаться, что выбор сохраняется, но это было визуальным багом:
