### ISSUE TITLE
ProgressSpin: Добавить новую размерную сетку

### ISSUE THREAD

**Issue by N1MBER** [gazprom-neft/consta-uikit#1443]
Стоит добавить еще хотя бы один размер: xl (а лучше еще 2xl), так как если разработчик делает сайт и хочет добавить спин лоудер на загрузку контента, нынешней размерной сетки ему может не хватить.

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=5867%3A11
Компонент называется - Timer
