### ISSUE TITLE
Calendar: Отсутствует 28 число в календаре

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1456]
![image](https://user-images.githubusercontent.com/75978078/130802741-4e014333-5c88-44b6-9152-ee450ce7d1bf.png)

**Comment by Ilyashis** [comment]
Исправлено
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=58%3A33602
