### ISSUE TITLE
ProgressStepBar: Дизайн

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1477]

**Comment by Ilyashis** [comment]
@Lyubavskaya @kolebayev 
На текущий момент реализован компонент одного размера и на одну тему. До апрува Ильи
И возможно я еще внесу правки по оптимизации компонента

Текущий вариант и примеры выложил в UI kit
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=55787%3A112460
