### ISSUE TITLE
ChoiceGroup: компонент не работает без указания флага multiple false

### ISSUE THREAD

**Issue by vlxdklv** [gazprom-neft/consta-uikit#1490]
ChoiceGroup: компонент не работает без указания флага multiple false, хотя он вроде как по умолчанию стоит в false.

![image](https://user-images.githubusercontent.com/82217595/131682316-a26c7524-5ee9-40d6-b670-7d7634ce3d28.png)

**Comment by gizeasy** [comment]
версия TS?

**Comment by gizeasy** [comment]
Да это так. Можешь направить пр с исправлениями типов?
