### ISSUE TITLE
Импорт компонентов ui-кита в проект на Next.js

### ISSUE THREAD

**Issue by BenuelBertran** [gazprom-neft/consta-uikit#155]
1) Развернуть проект на Next.js
2) Следовать инструкции по импорту компонентов: https://github.com/gpn-prototypes/ui-kit

![image](https://user-images.githubusercontent.com/23056113/83001837-f2b59d00-a014-11ea-8de2-0230597bec19.png)

OR

![image](https://user-images.githubusercontent.com/23056113/83001053-debd6b80-a013-11ea-9e16-615e906c31d4.png)

Expected result: Компонент добавлен на страницу и готов к использованию

![image](https://user-images.githubusercontent.com/23056113/83001403-5d1a0d80-a014-11ea-9b02-6e4bc5140ec3.png)

Actual result: 
error - ./node_modules/@gpn-design/uikit/__internal__/src/components/Attach/Attach.css
Read more: https://github.com/zeit/next.js/blob/master/errors/css-npm.md

![image](https://user-images.githubusercontent.com/23056113/83001437-6905cf80-a014-11ea-8914-e6b07473819a.png)

**Comment by BenuelBertran** [comment]
В описании проблемы https://github.com/vercel/next.js/issues/10975, ссылающуюся на ошибку "CSS Modules cannot be imported from within node_modules", предложено использовать следующий пакет https://www.npmjs.com/package/next-transpile-modules для транспиляции стороннего модуля. 

Выглядит неплохо, но к сожалению в моём случае не помогает. Попробовал добавить ui-kit разными способами, та же ошибка. 

![image](https://user-images.githubusercontent.com/23056113/83111989-243e6f00-a0ce-11ea-92b3-b6d7829c83c2.png)

![image](https://user-images.githubusercontent.com/23056113/83112342-b21a5a00-a0ce-11ea-882d-461f4d4e9682.png)

**Comment by gizeasy** [comment]
@BenuelBertran 
опробовал проделать все тоже самое. И да не работает. 
После того как настроил конфиги, мне удалось видеть рабочие стили
![image](https://user-images.githubusercontent.com/13190808/84030865-6ce30b80-a99d-11ea-9242-89c4b99539bd.png)
Но после обновления страницы, опять ошибка.

Очень странное поведение.
Я же правильно понимаю что next.js если в этих компонентах использовались css-modules то все нормально бы заработало?  next.jsу не нравится глобальные стили?

**Comment by daynin** [comment]
Сейчас не очень актуально, так как пока команда, которая столкнулась с ошибкой, отказалась от использования next.js
