### ISSUE TITLE
Не могу импортировать компонент Select 

### ISSUE THREAD

**Issue by Rndjester** [gazprom-neft/consta-uikit#1571]
Обновил консту, увидел в документации компонент Select, попытался добавить в проект, но импорта не предлагает, зашел в папку uikit и не нашел там директории "Select"

**Comment by gizeasy** [comment]
@Rndjester привет, только что обновился на 3.3.0 и все норм
![image](https://user-images.githubusercontent.com/13190808/133821438-2f099871-d5d6-4be8-942c-f7e0473bb532.png)

у тебя какая версия? может зависимости не подтянул?

**Comment by Rndjester** [comment]
![image](https://user-images.githubusercontent.com/55237393/133958745-cb051455-6be2-4e1d-8400-ce0ddbe9e42a.png)
![image](https://user-images.githubusercontent.com/55237393/133959366-369f4c97-2cbb-4a1b-86e4-be09dfd46256.png)

**Comment by Rndjester** [comment]
Попробовал снести и заново поставить, не помогло

**Comment by gizeasy** [comment]
@Rndjester с какой на какую версию обновлялся?

**Comment by gizeasy** [comment]
@Rndjester npm install или yarn?
Посмотри какая версия в yarn.lock или package-lock.json если другая снеси эти файлы и заново попробуй вытянуть зависимости

**Comment by Rndjester** [comment]
![image](https://user-images.githubusercontent.com/55237393/133996892-13996fe0-e6e5-4c58-8a29-64dbeb0a972f.png)
![image](https://user-images.githubusercontent.com/55237393/133997067-435ec49f-934a-4add-9391-25fb1a474a11.png)

**Comment by gizeasy** [comment]
не))
интересует версия `@consta/uikit` в yarn.lock или package-lock.json

**Comment by Rndjester** [comment]
вторая фотка это с package-lock.json

**Comment by gizeasy** [comment]
напиши мне в телеграме [gizeasy](https://t.me/gizeasy)
