### ISSUE TITLE
File: Поправить цвет у лоадера

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#158]
![image](https://user-images.githubusercontent.com/13190808/83049127-5b236f00-a053-11ea-8ac8-12cfc9afc0ea.png)

Кажется что нужно указать тему

**Comment by gizeasy** [comment]
@fooontic Мне не нравится цвет самого лоадера на темной теме, хочется оставить его таким-же как на светлой. Или норм?

**Comment by kolebayev** [comment]
Хардкодим цвет для спинера на все темы только внутри компонента File, стэндэлон спинер остается как был — на переменных.
Демо https://codesandbox.io/s/morning-water-r20fq?file=/src/styles.css
```
.ProgressSpin {
  color: #575b5e;
}
```
