### ISSUE TITLE
Изменить отображение фокуса для элемента Tabs

### ISSUE THREAD

**Issue by ilchukovaolga** [gazprom-neft/consta-uikit#162]
При фокусе на табе таб выделяется целиком по границам http://s.csssr.ru/UMYJTGU0M/2020-06-01-14-47-27-I9R0J.jpg

Наличие фокуса на элементе это хорошо, но обводка по прямоугольнику выглядит неестественно, так как у таба изначально видна только одна граница — нижняя.

Было бы лучше, если бы фокус был только снизу:

- Пример активного таба и фокуса на нем http://s.csssr.ru/U02GZ926T/2020-06-01-1535-1suuxel0n4.jpg
- Пример активного таба и фокусе не на активном табе http://s.csssr.ru/U02GZ926T/2020-06-01-1536-2uv8cp9cr9.jpg 

Ссылка на элемент: https://gpn-prototypes.github.io/ui-kit/?path=/story/ui-kit-tabs--playground

**Comment by fooontic** [comment]
Спасибо за идею. Мы подумаем над ней, но пока нас не сильно смущает текущий фокус у Таба, так что в ближайшее время в работу не пойдёт, как нам кажется.

**Comment by ilchukovaolga** [comment]
Жаль :(
