### ISSUE TITLE
Responses: Стиль и шрифт иллюстраций

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1651]
1. Поправить стилистику картинок (см. картинки Кодекса) 
Можно делать монохромные или цветные в рамках брендбука
Дополнить библиотеку картинок, если найдется еще что-то подходящее для интерфейсов
2. Цифры ошибок - сделать на ГПН DIN

**Comment by kolebayev** [comment]
нужно в код перенести
