### ISSUE TITLE
storybook: Убрать доки для разработчиков и вместо них поставить ссылки на основную репу

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1668]

**Comment by arhayka** [comment]
Договорились перенести в consta-uikit две доки из виджетов:
- Договорённости по оформлению кода https://consta-widgets-consta.vercel.app/?path=/docs/common-develop-arrangements-for-code-style--page
- Дизайн https://consta-widgets-consta.vercel.app/?path=/docs/common-develop-design--page
Переписать и показать Андрею и Илье.

Остальное удалить и поставить ссылки на главную страницу.

**Comment by arhayka** [comment]
https://github.com/gazprom-neft/consta-widgets-new/pull/58 — виджеты
В charts в деве, нужно выложить
