### ISSUE TITLE
TextField: баг с бордером после обновления до 3.7.0

### ISSUE THREAD

**Issue by lloydbanks** [gazprom-neft/consta-uikit#1673]
> Полные [правила оформления issue](https://consta-uikit.vercel.app/?path=/docs/common-develop-issues--page)

**Описание бага**
После обновления версии с 2.2.0 до последней на текущий день 3.7.0, у компонента `TextField` появился двойной border
![textfield-bug](https://user-images.githubusercontent.com/21862483/137356297-39d9d38a-0735-46fd-83ca-506a59fb756d.png)
Сравнил стили `TextField.css` по документации консты, со стилями из пакета, и они явно отличаются. И что интересно, если создать [чистую песочницу](https://codesandbox.io/s/affectionate-pike-tsx92?file=/src/App.js), то там рамок вообще нет.
![textfield-bug2](https://user-images.githubusercontent.com/21862483/137356301-0c1b554b-c149-494d-92f1-848c5956e89b.png)
Как чинится баг: как минимум убрать у него отступы и лишний border
![textfield-bug-fix](https://user-images.githubusercontent.com/21862483/137358726-07589e5a-b6aa-464d-814d-979dda1fd8df.png)

**Как воспроизвести баг** (опционально)  
Просто подключить компонент
`import { TextField } from "@consta/uikit/TextField";`
и использовать его в нужном месте
`<TextField placeholder="Default" />`

**Ожидаемое поведение** (опционально)  
Нормальное отображение компонента с рамками, как это продемонстрировано в примерах документации

> Если баг в коде, необходимо заполнить поля ниже ↧

**Версия Consta Kit**
3.7.0

**Параметры софта на компьютере:**

- ОС: Windows 10
- Браузер и его версия: Chrome Version 94.0.4606.81 (Official Build) (64-bit)

**Параметры смартфона:** (опционально)

- Модель:
- ОС:
- Браузер и его версия:

**Дополнительная информация**
Вообще, с этим обновлением появилось куча багов. То ошибки в консоли 
`Infinity is an invalid value for the height css style property at TabsFitModeDropdownWrapper`, то непонятные рамки повылазили в табах... В идеальном мире обратная совместимость не должна ломаться при обновлении, но тут прям многое пошло не так и выкатываться в прод похоже придется со старой версией.

**Comment by N1MBER** [comment]
@lloydbanks  Проверили свои css-файлы в собранном проекте, бордеры стоят только для TextField-InputContainer. Возможно у вас есть свои переписанные стили для TextField которые создают второй бордер. Создали пример в [чистой песочнице](https://codesandbox.io/s/modern-rgb-zkged?file=/src/App.js),  у вас компоненты были без обертки для тематизации.

**Comment by your-destiny** [comment]
> @N1MBER спасибо большое за ответ, изучу проблему на своей стороне и по результатам отпишусь.

Получилось ли у вас найти проблему подобного поведения?
