### ISSUE TITLE
ProgressStepBar: Замечания

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#1697]
1) странная размерная сетка размер `m` сильно большой, что по умолчанию выбран `s`
2) сейчас лейбл всегда должен присудствовать, что если я хочу показать только иконки и в тултипе вывести описание?

**Comment by Lyubavskaya** [comment]
по Сторибуку:

**Comment by N1MBER** [comment]
@gizeas, @Lyubavskaya,  проблема с лэйблом мне понятна, а что с размером делать, мне не ясно, в дизайне размер такой же. А также не совсем понятно что не так с сторибуком
