### ISSUE TITLE
ContextMenu: Человеческий обработчик кликов по меню

### ISSUE THREAD

**Issue by AntonS86** [gazprom-neft/consta-uikit#1729]
Для того что бы обработать клик, сейчас нам надо сделать следующее:
зарегистрировать обработчик на каждом пункте меню
```tsx
export const userItems: MenuItem[] = [
  {
    label: 'Сменить компанию',
    icon: IconTeam,
    onClick: () => console.log('1'),
  },
  {
    label: 'Выход',
    icon: IconExit,
    onClick: () => console.log('2'),
  }
];

<ContextMenu
    anchorRef={userRef}
    items={userItems}
    getLabel={(item) => item.label}
    getOnClick={(item) => item.onClick}
/>
``` 

предлагаю в апи добавить обработчик кликов, тк пункты меню могут хранится в бд и каждый раз добавлять обработчик не очень удобно

```tsx
const onClickHandler = (item: MenuItem) => item;
<ContextMenu
    anchorRef={userRef}
    items={userItems}
    getLabel={(item) => item.label}
    onClick={onClickHandler}
/>
```

**Comment by Lyubavskaya** [comment]
Sergey Katugin:
а у ContextMenu отлов клика как можно сделать?
у меня только костылями удалось сделать, по типу отлавливать общий клик, находить по DOM текст айтема и по этому тексу находить из массива айтемов
Хотелось бы, чтоб не приходилось делать такие обертки)

**Comment by gizeasy** [comment]
```tsx
onItemClick = (obj:{e: Event, item: ITEM}) => void
```
