### ISSUE TITLE
docs: Дизайн иллюстрации для доки по портальному архетипу

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1734]

**Comment by hell0anna** [comment]
смотреть тут https://www.figma.com/file/tChkF0Ba2YpGRd9gPNFyzd/Images-%5Bignore%5D?node-id=1609%3A24552

[pics.zip](https://github.com/gazprom-neft/consta-uikit/files/7618076/pics.zip)

**Comment by hell0anna** [comment]
https://www.figma.com/file/tChkF0Ba2YpGRd9gPNFyzd/Images-%5Bignore%5D?node-id=1661%3A22160

может быть достаточно одной картинки? 
со схематичным интерфейсом

**Comment by hell0anna** [comment]
версия 3.1 финальная
![pic_v3 3](https://user-images.githubusercontent.com/51019093/145989351-b7bb32cc-b150-42bf-97b5-d29f08e979f8.jpg)
