### ISSUE TITLE
Header: доработать адаптивность

### ISSUE THREAD

**Issue by hell0anna** [gazprom-neft/consta-uikit#1744]
привет!
нужно доработать адаптивность для компонента моб устройств в сторибуке
макет тут https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=62901%3A125259

думаю можно обсудить словами как именно дорабатывать, тк могут быть вопросики
спасибо

**Comment by andreynovikov** [comment]
Что-то нужно сделать с меню. У нас в нём много пунктов, и даже если просто раскрыть браузер не на весь экран, то получается полный кошмар. Особенно, если в названии пункта есть пробел. Почему нельзя там использовать функционал табов?

**Comment by hell0anna** [comment]
> Что-то нужно сделать с меню. У нас в нём много пунктов, и даже если просто раскрыть браузер не на весь экран, то получается полный кошмар. Особенно, если в названии пункта есть пробел. Почему нельзя там использовать функционал табов?

@andreynovikov  привет! хотим разобраться с проблемой, но сейчас не совсем понятно о чем речь. Приложите пожалуйста скриншоты. Спасибо!

**Comment by andreynovikov** [comment]
С широким окном выглядит так:
![](https://user-images.githubusercontent.com/2943625/145809237-3bbf1a2b-4653-4b70-ae4d-77454179eddf.png)

С узким окном выглядит так:
![](https://user-images.githubusercontent.com/2943625/145809243-b05193df-6c11-4e6a-a822-045dc49c0bce.png)
И, нет, бейджики тут не причём, я их отключал, "Учётные записи" так и выглядят, и всё по-прежнему съезжает наверх.

Вообще, может я как-то не так инициализирую окружение, потому что, когда я включаю режим эмуляции устройств, всё вообще разъезжается вкривь и вкось, даже внутренний контент (см. ширину таблицы). Вертикально:
![](https://user-images.githubusercontent.com/2943625/145810139-ada01850-db64-4233-b1ab-4732b68e1ef5.png)
Горизонтально:
![](https://user-images.githubusercontent.com/2943625/145810117-b8b03f0d-e172-456a-8743-0d29c352b196.png)

Обрамляющий html выглядит так:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    html, body, #app {
      height: 100vh;
      padding: 0;
      margin: 0;
    }
  </style>
</head>
<body>
<div id="app">
    <!-- React will load here -->
</div>
</body>
</html>
```

**Comment by gizeasy** [comment]
На данный момент нет возможности как-то скрывать пункты меню которые не входят в экран. 
Сейчас в работе хеадер с возможностью адаптации под разные расширения
