### ISSUE TITLE
Header: Убрать бургер из десктопной шапки 

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1752]
Убрать иконку бургера из шапки десктопных размеров, для всех тем, контент сдвинется влево. В макете для мобилы оставляем
<img width="635" alt="изображение" src="https://user-images.githubusercontent.com/24884175/141285078-93bb806d-7972-4641-962f-4f374a424c1c.png">

**Comment by hell0anna** [comment]
готово https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=2411%3A37833
