### ISSUE TITLE
Header: Стилизовать табы в хэдере под компонент Tabs

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#1753]
<img width="825" alt="изображение" src="https://user-images.githubusercontent.com/24884175/141285512-f2d4898e-93a9-42a0-999d-86e563e6d360.png">

так сложилось, что табы хэдера визуально отличаются от [Tabs](https://consta-uikit.vercel.app/?path=/story/components-tabs--playground). шапку в коде делали раньше, чем компонент.

Задача: привести визуал табов в шапке к визуалу компонента Tabs.
Как минимум поправить полоску активного элемента, паддинги — по ситуации (если не будет мешать выравниванию по бейслайну)

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=3758%3A0

**Comment by hell0anna** [comment]
+ добавить  модификацию на сворачивание (адаптивность)
