### ISSUE TITLE
hooks: Проверить документацию по хукам

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1756]
- Не надо ли что-то поправить/дополнить?
- Единая структура? 
- Что-то явно не дописано в доке по useDebounce (в конце двоеточие)

**Comment by arhayka** [comment]
Посмотрела хуки, мне кажется, что там всё ок! Можно добавить оглавление, но доки в основном очень короткие, оглавление будет только мешать.
