### ISSUE TITLE
Combobox: Не найдено, даже если значения нашлись

### ISSUE THREAD

**Issue by Nikita7795** [gazprom-neft/consta-uikit#1781]
при поиске значение в этом компоненте, если даже нашлись какие-то значения, снизу есть подпись "Не найдено"
<img width="517" alt="Снимок экрана 2021-11-17 в 16 15 45" src="https://user-images.githubusercontent.com/69715667/142207729-4ef9eb78-30f9-47df-a666-1ccfe11368f3.png">

**Comment by afbagautdinov** [comment]
+
