### ISSUE TITLE
Slider: Доработать в Figma

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1799]
Несколько отличий компонента Slider в макете и в том, что реализовано:
- есть вариант с передачей нескольких значений в steps (в макете нет)
- есть вариант с подписью (в макете нет)
- есть вариант со статусами, которые влияют только на подпись (в макете нет)
- есть вариант с прерывистой линией + иконка + textField (в макете нет, если включать иконку, линия переключается на сплошную)

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=67568%3A129967
