### ISSUE TITLE
Компонент: DatePicker свойство withIcon

### ISSUE THREAD

**Issue by asa-45** [gazprom-neft/consta-uikit#1813]
Компонент: DatePicker

Свойство withIcon не включает отображение иконки календаря

http://prntscr.com/20zr522
http://prntscr.com/20zqsfr

**Comment by gizeasy** [comment]
@asa-45 
https://consta-uikit.vercel.app/?path=/docs/components-datepicker--playground
посмотрите документацию, за проброс иконки отвечают свойства 
`leftSide` `rightSide` и также поля с `multiple` можно поставить отдельно для каждого поля
