### ISSUE TITLE
TextField: В размерах S и XS в вариантах оставлены скрытые слои

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1826]
Textarea — в размерах S и XS в вариантах оставлены скрытые слои.
Было бы лучше иметь корректные варианты, чтобы систему не делать тяжёлой

**Comment by linturaven** [comment]
Готово
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/?node-id=5164%3A84922
