### ISSUE TITLE
Header: Подчеркивание в табах не масштабируется с текстом в ширину

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1827]
Хедер — табы: подчеркивание не масштабируется с текстом в ширину, в отличие от обычных табов

**Comment by hell0anna** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=2411%3A37833
вроде поправила, ждет публикации
