### ISSUE TITLE
docs: Перечень репозиториев и библиотек в Figma Community 

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#1829]
Перечень репозиториев с коротким описанием, что находится в каждом из них. (со ссылками)
Перечень библиотек в Figma Community с коротким описанием, что находится в каждом из них. (со сылками)
Нужно для документации на PaaS Hub

**Comment by arhayka** [comment]
Готово: https://docs.google.com/document/d/1cpZcNviz3rb9rQxj9WAnc2ezE29ed-oiejW3y8Wydbs/edit

**Comment by arhayka** [comment]
Договорились добавить этот список в документацию
