### ISSUE TITLE
useDimension: создать хук 

### ISSUE THREAD

**Issue by N1MBER** [gazprom-neft/consta-uikit#1856]
Создать хук для отслеживания размерности элемента / экрана

Содержит 2 необязательных поля:
* sizeMap - объект разрешений и названий
* currentRef - рефка или объект DOM

**Comment by gizeasy** [comment]
320, 360, 480, 720, 960, 1020, 1200, 1400, 1600, 1800, 2000, 2200, 2400,

1200 = m

**Comment by gizeasy** [comment]
{ isMobile: 0, isDesctop: 460 } такое можно прокинуть, и хук должен возвращать ключи обекта
