### ISSUE TITLE
Отображения поля у кнопок в заголовке таблицы при наведении

### ISSUE THREAD

**Issue by hidmitry** [gazprom-neft/consta-uikit#1862]
В дизайн библиотеке при наведении на кнопку в заголовке поле у кнопки не отображается 

<img width="465" alt="Screenshot 2021-12-16 at 16 53 53" src="https://user-images.githubusercontent.com/95356759/146385744-7c890c86-9ee9-4425-b7d8-d516cf3422c3.png">

[Ссылка](https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=5141%3A74365)

А в библиотеке компонентов отображается

<img width="516" alt="Screenshot 2021-12-16 at 16 54 58" src="https://user-images.githubusercontent.com/95356759/146385883-d20296d0-3da8-4c1b-984d-ad3578faaf49.png">

[Ссылка](https://consta-uikit.vercel.app/?path=/story/components-table--with-icon)

**Comment by hell0anna** [comment]
поправлено https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=1871%3A36244
