### ISSUE TITLE
ContextMenu: Цвет текста в disabled items

### ISSUE THREAD

**Issue by levi2015mik** [gazprom-neft/consta-uikit#1899]
Если в контекстном меню присутствуют неактивные пункты указанные через функцию getOnClick, в ранних версиях они consta цвет их текста был более бледным, сейчас они черные, как по дефолту. 
Проблема касается только стиля. Неактивные пункты меню на клик не реагируют, что корректно.

**Comment by N1MBER** [comment]
@levi2015mik Сейчас для того чтобы определить является ли пункт неактивным необходимо прокидывать функцию в `getDisabled` в которой вы уже сами определяете как определять неактивность конкретного пункта. Так цвета выставляются правильно

**Comment by levi2015mik** [comment]
К сожалению нет. Я сейчас использую версию 2.2.1
Там тоже применяется функция getDisabled. Меню выглядит так https://ibb.co/frcsyRJ
В новой версии, 3.12.3 оно же выглядит так https://ibb.co/SN4N0k6
В стилях класс .ContextMenuItem_disabled отвечающий за бледный цвет перекрывается стилем из .Text_view_primary
https://ibb.co/YW0XRbH
https://ibb.co/4WcGYGy
