### ISSUE TITLE
Не стоит исключить из tsconfig-а стори и тесты

### ISSUE THREAD

**Issue by nekitk** [gazprom-neft/consta-uikit#253]
Сейчас в tsconfig в exclude добавлены файлы стори и тестов:
https://github.com/gpn-prototypes/ui-kit/blob/master/tsconfig.json#L29-L32

Стоит включить эти файлы в проверку и поправить соответствующие ошибки.
Стори и тесты компонентов не должны содержать ts-ошибок — это позволит удостовериться, что в них компоненты и тестируемые функции используются правильно.

**Comment by gizeasy** [comment]
проблема в том что игноры там для того чтоб эти файлы не попали в сборку, скорее всего надо будет либо условие добавить, либо отдельный конфиг для сборки проекта сделать.
