### ISSUE TITLE
Radio: объединить RadioGroup с Радио 

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#266]
! после написания документации

Надо доделать стори с радиокнопками. Нужно сделать несколько радио в одной стори, и нормальное переключение между ними не через нобы, а по клику на сами радио.

**Comment by gizeasy** [comment]
Перенесу на следующий спринт, хочется в этом задаче использовать `useChoiceGroup`

**Comment by arhayka** [comment]
Перенесла часть доки в RadioGroup. А так вроде решили, что оставляем эту доку для тех, кто хочет использовать радиокнопку отдельно от группы. В этом случае, кажется, добавлять несколько радио в одну стори не нужно.
