### ISSUE TITLE
Несовместимость типов

### ISSUE THREAD

**Issue by hitmanet** [gazprom-neft/consta-uikit#282]
Сейчас, если использовать компонент Field из react-final-form с TextField, то появится вот такая ошибка
![image](https://user-images.githubusercontent.com/33551076/88644624-dd6bf600-d0cb-11ea-938e-1a3c4e263ea4.png)
Появляется необходимость в приведении типов, что создает неудобства. Возможно, это связано с тем, что TextField юзает типы дива

**Comment by gizeasy** [comment]
Может стоит для FinalForm сделать компонент обертку `TextFieldFinalForm`?

**Comment by gizeasy** [comment]
@hitmanet ??

**Comment by hitmanet** [comment]
> @hitmanet ??

Мы у себя так и сделали в итоге
