### ISSUE TITLE
Добавить в доку для контребьютеров описание файловой структуры

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#290]
## Структура компонентов

```
components/                             
    Block/                                  # Директория блока
        __tests__/                          # Директория тестов
            Block.test.tsx                  # Рефлизация теста блока Block
            helpers.test.tsx                # Реализация теста вспомогательных функций
        __mocks__/                          # Директория для моковыйх данных
            data.mock.tsx                   # Моковые данные для стори и/или тестов
        __stories__/                        # Директория для стори
            examples/                       # Директория для примеров
                BlockExampleName/           # Директория блока BlockExampleName
                    BlockExampleName.css    # Реализация блока BlockExampleName в технологии CSS
                    BlockExampleName.tsx    # Реализация блока BlockExampleName в технологии TS
            Block.mdx                       # Документация для Block
            Block.stories.css               # Cтили для стори Block
            Block.stories.tsx               # Реализация стори Block
        BlockName/                          # Директория блока используемого в родительском блоке
            BlockName.css                   # Реализация блока BlockName в технологии CSS
            BlockName.tsx                   # Реализация блока BlockName в технологии TS
        Block.css                           # Реализация блока Block в технологии CSS
        Block.tsx                           # Реализация блока Block в технологии TS
```

### Дочерний компонент - не элемент а блок.
Все дочерние компоненты, должны быть реализованы как Блоки в БЭМ. Их название должно быть с префиксом равным названию родительского блока, пример:
```
Button/
    ButtonIcon/
        ButtonIcon.tsx
        ButtonIcon.css
    Button.tsx
    Button.tsx
```
### Дочерний компонент не может быть родителем других компонентов.
не правильно:
```
List/
    ListItem/
        ListItemButton/
            ListItemButton.tsx
            ListItemButton.css
        ListItem.tsx
        ListItem.css
    List.tsx
    List.css
```
правильно:
```
List/
    ListItem/
        ListItem.tsx
        ListItem.css
    ListItemButton/
        ListItemButton.tsx
        ListItemButton.css
    List.tsx
    List.css
```

### Наименование CSS классов
наименование должно быть по БЭМ: `Block-Element_ mod` или `Block-Element_ mod_value`
название блока должно совпадать с названием компонента.

**Comment by gizeasy** [comment]
```
components/                             
    Block/                                  # Директория блока
        __tests__/                          # Директория тестов
            Block.test.tsx                  # Рефлизация теста блока Block
            helpers.test.tsx                # Реализация теста вспомогательных функций
        __mocks__/                          # Директория для моковыйх данных
            data.mock.tsx                   # Моковые данные для стори и/или тестов
        __stories__/                        # Директория для стори
            examples/                       # Директория для примеров
                BlockExampleName/           # Директория блока BlockExampleName
                    BlockExampleName.css    # Реализация блока BlockExampleName в технологии CSS
                    BlockExampleName.tsx    # Реализация блока BlockExampleName в технологии TS
            Block.mdx                       # Документация для Block
            Block.stories.css               # Cтили для стори Block
            Block.stories.tsx               # Реализация стори Block
        Element/                            # Директория элемента Block-Element
            Block-Element.css               # Реализация элемента Block-Element в технологии CSS
            Block-Element.tsx               # Реализация элемента Block-Element в технологии TS
        Block.css                           # Реализация блока Block в технологии CSS
        Block.tsx                           # Реализация блока Block в технологии TS
```

проблемы структуры
сейчас дочерние компоненты предлагается делать БЭМ-элементами основного компонента-блока
это может привести к следующим проблемам:
1) один из элементов внутреннего компонента может перебить элемент большого компонента. допустим, и в таблице, и в его подкомпоненте может быть элемент кнопки. если мы обоим этим кнопкам зададим класс cn('Button'), то стили этих кнопок наложатся друг на друга.
2) так же частая практика в блоке называть обёртку компонента элементом с аналогичным названием. например: .Table -> .Table-Cell -> .Cell . в текущем варианте, придётся городить не самые осмысленные названия с суффиксами Wrapper, Container и т.п.
3) стили одного блока размазываются по нескольким файлам. мне кажется, правильнее хранить стили одного блока в одном файле.
4) чтобы понять, как можно назвать элемент в дочернем компоненте так, чтобы ни с кем не законфликтоваться нужно посмотреть вёрстку главного компонента и всех его подкомпонентов, чтобы убедиться, что желаемое имя нигде не используется.

1) Можно договориться что если элемент выносим в отдельный компонент то назвать используемые элементы в нутри этого компонента стоит с префиксом родителя, к примеру:
```
<div className={cnBlock('Item')}>
  <div className={cnBlock('ItemIcon')}>

  </div>
</div>
```

тогда проблем с пересечением стилей не будет.
3) Договориться не определять стили элементов в блоке, ели элемент вынесен в отдельный компонент. Всегда есть возможность указать переменную в блоке и использовать ее в элементе. Если не получается через переменные то можно использовать модификаторы и из блока прокидывать нужные модификаторы в элемент. Таким образом проблема описания одного элемента в разных файлах уйдет.
4) Уйдет если соблюдать пункт 1

**Comment by fooontic** [comment]
Не понял, что значит BlockName? 
Можно первую схему на примере Button расписать?

**Comment by fooontic** [comment]
А... кажется понял. Это типа дочерний блок?

**Comment by gizeasy** [comment]
@fooontic да, верно. Ну и название у него начинается с названия блока родителя.
