### ISSUE TITLE
Сборка: В типизацию подмешивается лишний аттрибут для элементов

### ISSUE THREAD

**Issue by evless** [gazprom-neft/consta-uikit#305]
Столкнулся с проблемой в проекте, где нет в зависимостях сторибука. При подключении ui-kit библиотеки и использовании любого компонента падала типизация с ошибкой http://s.csssr.ru/U7RQKLD4J/2020-07-31-15-58-36-i085y.jpg

Выяснилось, что в сторибуке есть зависимость `emotion`, которая в глобальные типы подмешивает `css` аттрибут, который попадает в финальную сборку ui-kit.

### Хак для тех, кто тоже столкнулся с этой проблемой
Нужно в глобал добавить тип
```
declare module 'react' {
  interface DOMAttributes<T> {
    css?: any
  }
}
```

**Comment by maksim-kononov-csssr** [comment]
TS посылает тысячу проклятий в консоль из-за этой ошибки. Запинил ишью
<img width="1269" alt="Снимок экрана 2020-08-05 в 10 21 33" src="https://user-images.githubusercontent.com/45596310/89384530-e467b980-d706-11ea-8cb0-4c192b6b817b.png">

**Comment by gizeasy** [comment]
Нашел в какой момент проблема появилась.
Как только любой компонент из storyBook импортируешь, так в react подмешиваются типы из emotions.

**Comment by gizeasy** [comment]
вроде как поправили эту проблему в emotions
https://github.com/emotion-js/emotion/issues/1800

**Comment by evless** [comment]
Ошибка не ушла, а просто превратилась в другую теперь:
http://s.csssr.ru/U7RQKLD4J/2020-08-17-16-32-51-zw9vq.jpg

**Comment by nekitk** [comment]
стоит попробовать исключить типы emotion из tsconfig-а во время сборки. возможно, это поможет избежать патчинга глобальных типов.
