### ISSUE TITLE
Поповер: продумать логику выбора направления разворачивания, если не хватает места

### ISSUE THREAD

**Issue by nekitk** [gazprom-neft/consta-uikit#313]
Перенёс обсуждение из https://jira.csssr.io/browse/GDC-532

Ниже говорится про тултип, но в реалиях Консты это уже компонент Popover.

**Проблема**: Если тултипу не хватает места, то он разворачивается вверх и обрезается. Промотать страницу вверх и обозрет тултип невозможно, тк, судя по положению скролла, мы и так находимся на самом верху.

**Комментарий, почему так происходит и что можно сделать**:
> Для тултипа роадмапа задано дефолтное положение upRight. Если тултипу хватает места, он разворачивается в него. Если не хватает места открыться ни в какую сторону, то тоже берётся дефолтное положение.
> 
> По части разворачивания вверх есть особенность работы браузера: если контент вылезает за левую или верхнюю часть экрана, то скролл не появляется. Если же контент вылезает за правую или нижнюю часть экрана, то скролл появляется.
> 
> Получается, такие проблемы можно решить, если в качестве запасного направления (когда никуда не влезаем) брать не дфеолтное, а какое-нибудь из направлений вправо или вниз. Но это стоит делать на уровне всех тултипов и согласовывать с Вадимом. Возможно, это стоит править уже после переноса тултипа в uikit. Если решим делать, то лучше будет оформить как отдельную задачу.

**Ответ Вадима**:
> Да, так, кажется логичнее. Но после переноса тултипа в нам этот кусок вообще сильно изменится и возможно надо будет заново к нему вернуться. Предлагаю это пока на холд поставить

**Comment by gizeasy** [comment]
наметил 2 решения:
1) Добавлять скрол к боди так чтоб весь тултим возможно было просмотреть.
2) Добавлять скрол в тултип выводя его в максимально большую сторону для раскрытия.
