### ISSUE TITLE
Attach. Исправить расстояние между строками в заголовке

### ISSUE THREAD

**Issue by ilchukovaolga** [gazprom-neft/consta-uikit#316]
Маленькое расстояние между строками в названии, названием и сведениями о файле в компоненте загрузки файлов. Строки слипаются, сложно читать.

ОР в макете Vega-2: https://s.csssr.ru/UMYJTGU0M/2020-07-30-17-31-44-nPL2y.jpg
ФР: https://s.csssr.ru/UMYJTGU0M/2020-07-30-17-31-35-VtU6e.jpg

Компонент: https://ui-kit.gpn.vercel.app/?path=/story/components-attach--playground
Ссылка на макеты: https://www.figma.com/file/kXPRVpLhqNfBm9DBOoaE9X/VEGA-2.0-%7B-dev-%7D?node-id=617%3A871

**Comment by gizeasy** [comment]
@fooontic что думаешь?

**Comment by fooontic** [comment]
Пока верим компоненту в Сторибуке. В коде такие расстояния для большей экономии места. Надо посмотреть на бóльших примерах в реальности и если надо будет поправим потом и везде обновиться. Пока оставляем как есть в коде.

**Comment by ilchukovaolga** [comment]
@fooontic а какие примеры в реальности вам нужны? Вот как это будет выглядеть в Веге-2 http://s.csssr.ru/UMYJTGU0M/2020-08-14-11-58-35-5da7u.jpg

Строки слишком близко находятся друг к другу. В макетах выглядит и воспринимается гораздо лучше, так как отступ между строками немного больше.

**Comment by fooontic** [comment]
Пока на наш взгляд лучше выглядит в коде. Место экономится и подпись не выпадает за нижнюю ось иконки. Заменим в макетах.
