### ISSUE TITLE
ChoiceGroup: пропадает палочка при view="secondary"

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#351]
Шаги воспроизведения:

1. Открыть стори ChoiceGroup: https://ui-kit.gpn.vercel.app/?path=/story/components-choicegroup--playground
2. Выбрать view="secondary"
3. Выбрать "два", а затем избавиться от фокуса

Результат: правая палочка отсутствует.
![image](https://user-images.githubusercontent.com/22579048/90739305-0d33a580-e2e8-11ea-9d93-f2caefdc76a2.png)

Если выбрать "один":
![image](https://user-images.githubusercontent.com/22579048/90740002-3f450780-e2e8-11ea-8ffc-f3713b8b29b7.png)

**Comment by fooontic** [comment]
О как! Спасибо большое. Разберёмся и обязательно поправим в следующем спринте

**Comment by fooontic** [comment]
поправлено в ПР #367
