### ISSUE TITLE
Правки после переезда

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#374]
поменять ссылки на gitHub
Поменял ять ссылки на стенд

**Comment by arhayka** [comment]
FileField

1) Компонент для выбора фалов. 

—> 

Компонент для выбора файлов.

2) Пользователь может выбрать файлы на своем компьютере чтобы куда-то загрузить или отправить.

 —> 

Пользователь может выбрать файлы на своем компьютере, чтобы куда-то загрузить или отправить.

3)  Табличка вообще не моя, посмотри, плиз, там точно все свойства описаны?

4) Ссылка на DOM елемент инпута

и все атрибуты input (отвалилось из таблички)

 —> 

Ссылка на DOM-элемент input и все атрибуты input

(Кажется, должно быть так, но я не уверена)

**Comment by arhayka** [comment]
**About**

1) дополнять базовых

 —> 

дополнять базовые

2) заголовок 4 слоя: удалить

3) в списке убрать повторы (Тема Тема, Каркас Каркас, Паттерны Паттерн)

**Comment by arhayka** [comment]
**BasicSelect**

Вообще это надо переписывать, но давай поправим ошибки хотя бы.

1)
BasicSelect — компонент реализующий элемент управления меню опций (нативного <select>).
—>
BasicSelect — компонент, реализующий элемент управления меню опций (нативного <select>).

2) В табличке нужно |  между значениями заменить на что-то другое (я меняю на / или ,). Иначе табличка крашится.

**Comment by arhayka** [comment]
**Checkbox**

1) Имя игнпута в DOM —> Имя input в DOM

2) Ссылка на DOM-элемент игнпута —> Ссылка на DOM-элемент input

**Comment by arhayka** [comment]
ChoiceGroup

1) Описание у name в табличке —> Имя input в DOM

**Comment by arhayka** [comment]
**Radio**

1. В табличке нужно | между значениями заменить на что-то другое (я меняю на / или ,). Иначе табличка крашится.

Где менять: 
- checked  `boolean | undefined`


2. checked — описание убежало, нужно добавить

Отмечает радиокнопку выбранной

**Comment by arhayka** [comment]
**SnackBar**

Нужно переписывать, но пока просто поправим запятые.

1. Массив элементов. Если не передавать onAutoClose то по истечению таймера будет срабатывать onClose

—>

Массив элементов. Если не передавать onAutoClose, то по истечению таймера будет срабатывать onClose

**Comment by arhayka** [comment]
**Switch**

1. Ссылка на DOM-элемент ипута —> Ссылка на DOM-элемент input

**Comment by arhayka** [comment]
Table

1. Компонент заглушка для отображения когда нет данных —> Заглушка, отображается, когда в таблице нет данных

**Comment by arhayka** [comment]
Text

1. Заголовок в таблице По умполчанию —> По умолчанию

2. view —  не хватает | между 'warning', primary — поэтому описание съехало в графу По умолчанию

**Comment by arhayka** [comment]
Tooltip

В примерах во всплывающем окне показывается текст **Контент поповера**. Надо — **Контент тултипа**

**Comment by gizeasy** [comment]
Tooltip не получается, примеры беруться из поповера. создам ишшью отдельно
