### ISSUE TITLE
Добавить для Tag режим без обработчиков

### ISSUE THREAD

**Issue by c1n1k** [gazprom-neft/consta-uikit#378]
В мультиселекте используются теги в режиме `cancel`. В состоянии селекта `disabled` нужно отображать теги без кнопки очищения, подходит режим `button`, но нужны для него обработчики. Необходимо стостояние без обработчиков

**Comment by gizeasy** [comment]
@fooontic может добавить модификатор disable?

**Comment by gizeasy** [comment]
решили сделать mode_info
