### ISSUE TITLE
Таблица: Двухуровневые заголовки

### ISSUE THREAD

**Issue by nedradigital** [gazprom-neft/consta-uikit#396]
В проекте ПортУ возникла необходимость добавления в таблицу двухуровневых заголовков.

Скрин с макетом:
![Screenshot at Sep 11 16-54-00](https://user-images.githubusercontent.com/69645013/92933827-6f974600-f44f-11ea-8e7b-ec8ad0b9dd0e.png)

**Comment by nedradigital** [comment]
Как основной вариант решения рассматриваем добавление возможности расширить параметр columns группировкой по столбцам

```
const columns = [
  {
    groupTitle: 'Январь',
    columns: [{
      title: 'БП млн. тонн',
      accessor: 'BP-jan',
      align: 'right',
      width: 100,
    },
    {
      title: 'Портфель млн. тонн',
      accessor: 'package-jan',
      align: 'right',
      width: 100,
    },
    {
      title: 'Дельта млн. тонн',
      accessor: 'delta-jan',
      align: 'right',
      width: 100,
      sortable: true
    }]
  },
  {
    groupTitle: 'Февраль',
    columns: [{
      title: 'БП млн. тонн',
      accessor: 'BP-feb',
      align: 'right',
      width: 100,
    },
    {
      title: 'Портфель млн. тонн',
      accessor: 'package-feb',
      align: 'right',
      width: 100,
    },
    {
      title: 'Дельта млн. тонн',
      accessor: 'delta-feb',
      align: 'right',
      width: 100,
      sortable: true
    }]
  },
];
```
Коллеги, что думаете?

**Comment by gizeasy** [comment]
вопросы к обсуждению:
1) Может тогда реализуем возможность не двухуровневых а многоуровневых? смотреть на `columns` и понимать какой уровень заголовка.
2) Будет ли возможность одну колонку обычной, а вторую многоуровневую?

**Comment by gizeasy** [comment]
@nekitk

**Comment by nedradigital** [comment]
> вопросы к обсуждению:
> 
> 1. Может тогда реализуем возможность не двухуровневых а многоуровневых? смотреть на `columns` и понимать какой уровень заголовка.
> 2. Будет ли возможность одну колонку обычной, а вторую многоуровневую?

1.  Выглядит не сильно сложнее, нам все равно придется разбивать уровни на ряды, почему бы не сделать это рекурсивно :)
2. Можем сделать, например прямо в лоб, добавить обработчик в начале, который выровняет нам уровни во всех колонках
