### ISSUE TITLE
Таблица должна поддерживать возможность сортировки по нескольким столбцам одновременно. 

### ISSUE THREAD

**Issue by nedradigital** [gazprom-neft/consta-uikit#400]
При сортировке по нескольким столбцам таблица должна отображать порядок столбцов в сортировке: по какому столбцу производится сортировка в первую очередь, по какому - во вторую (при равных значениях в первом столбце) и так далее.

**Comment by fooontic** [comment]
Неактуально. Причина расписана здесь https://github.com/gazprom-neft/consta-uikit/pull/577#issuecomment-722181917

Возможные варианты решения должны реализовываться вне компонента таблицы: 
<img width="3504" alt="Frame 1" src="https://user-images.githubusercontent.com/12127740/101786117-9e848d00-3b0e-11eb-8124-2542a7a3ccc8.png">
