### ISSUE TITLE
Table: Добавить механизм горизонтальной прокрутки

### ISSUE THREAD

**Issue by olegdenisov** [gazprom-neft/consta-uikit#402]
Для удобство горизонтальной проекрутки предлагаю добавить возможноть прокрутки через drag или прокрутку скроллом при подведении мыши к горизонтальному скроллу

**Comment by Lyubavskaya** [comment]
Есть модификация с зафиксированной колонкой, которая дублирует поведение: https://consta-uikit.vercel.app/?path=/story/components-table--with-sticky-column
