### ISSUE TITLE
Пометить старый пакет как deprecated и добавить ссылку на новый

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#436]
через cli делается:
https://docs.npmjs.com/cli/deprecate

указанное сообщение появится в шапке пакета на странице

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/96428962-0dc5bb00-1209-11eb-95b3-6b8548a42ac3.png)

npm ругается на отсутствие пакета

**Comment by fooontic** [comment]
Не получилось.
