### ISSUE TITLE
Table: Оптимизация таблицы

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#442]
Столкнулись с проблемой производительности таблицы из консты. Нам необходимо вывести 2-3 тысячи строк по паре десятков столбцов. (Администратор- показать все загруженные проекты). При этом от пагинации мы отказались, то есть необходимо выводить все строки в таблице со скроллом. В компоненте не применяются средства оптимизации по типу react-virtualized, из-за чего она зависает намертво.

**Comment by dmitriykorsakovnedra** [comment]
Планируем взять в работу на этой неделе.

Для виртуализации предварительно берем react-virtalized.
Использование виртуалиации накладывает ограничение на высоту строк таблицы, они должны быть фиксированными для корректной работы виртуализатора.

Предлагаем сделать функцию виртуализации опциональной, и в случае ее выбора, будет обязательным указание высоты строки.

@gizeasy, @fooontic, что думаете?

**Comment by gizeasy** [comment]
> Планируем взять в работу на этой неделе.
> 
> Для виртуализации предварительно берем react-virtalized.
> Использование виртуалиации накладывает ограничение на высоту строк таблицы, они должны быть фиксированными для корректной работы виртуализатора.
> 
> Предлагаем сделать функцию виртуализации опциональной, и в случае ее выбора, будет обязательным указание высоты строки.
> 
> @gizeasy, @fooontic, что думаете?

Скорее всего надо будет писать свой хук виртуализации. Так как ограничить высоту строк нельзя. Предлагаю отталкиваться не от высоты, так как мы не знаем какой высоты будет контент а от штук, к примеру взять N = 300  отрендеренных строк   думаю не будет тормозов если их все показать. Далее на каждый скрол проверять уже по пиксельно на сколько мы приблизились к краю этих отрендеренных, и к примеру 500 пикселей до края если остаётся то рендерим дальше на N строк. С верху мы уже знаем сколько у нас пикселей занимает контент и этот отступ оставляем. С низу всегда к примеру 1000 пока не дойдем до конца. И как только дошли до конца так уже запоминаем высоты всей таблицы чтобы больше не прибавлять на абум 1000 пикселей вниз от края контента. И нужно ещё учесть ширину таблицы, если она меняется то стирать значения высоты таблицы. И ещё я пока не придумал как обойти кейс когда мы отсколились в середину таблицы, и меняем ресайзом ширину таблицы, и у нас верху поменялась высота, и мы не знаем на какое значение, тут либо в последствии при скроле вверх при подгруске новых элементов подстраивать скрол так чтобы все элементы входили в экран или не было белого полотна, или  при ресайзе просто отскроливать таблицу в самый верх и считать потом все по новой.

**Comment by dmitriykorsakovnedra** [comment]
> 
> Скорее всего надо будет писать свой хук виртуализации. Так как ограничить высоту строк нельзя. Предлагаю отталкиваться не от высоты, так как мы не знаем какой высоты будет контент а от штук, к примеру взять N = 300 отрендеренных строк думаю не будет тормозов если их все показать. Далее на каждый скрол проверять уже по пиксельно на сколько мы приблизились к краю этих отрендеренных, и к примеру 500 пикселей до края если остаётся то рендерим дальше на N строк. С верху мы уже знаем сколько у нас пикселей занимает контент и этот отступ оставляем. С низу всегда к примеру 1000 пока не дойдем до конца. И как только дошли до конца так уже запоминаем высоты всей таблицы чтобы больше не прибавлять на абум 1000 пикселей вниз от края контента. И нужно ещё учесть ширину таблицы, если она меняется то стирать значения высоты таблицы. И ещё я пока не придумал как обойти кейс когда мы отсколились в середину таблицы, и меняем ресайзом ширину таблицы, и у нас верху поменялась высота, и мы не знаем на какое значение, тут либо в последствии при скроле вверх при подгруске новых элементов подстраивать скрол так чтобы все элементы входили в экран или не было белого полотна, или при ресайзе просто отскроливать таблицу в самый верх и считать потом все по новой.

Тут не очень хорошо, что мы, резко потянув за бегунок, не сможем оказаться в самом конце, придется добираться "прыжками". Да и так как зависим от ширины экрана и от ресайзера в самой таблице, то прибавлять наобум придется всегда, то есть добираться прыжками будем как вверх так и вниз. Скроллить таблицу вверх при ресайзе решение интересное, но это не очень очевидное поведение, ограничение высоты строки как по мне выглядит меньшим злом.

**Comment by daynin** [comment]
@gizeasy 

Точно не вариант закладывать какие-то значения смещений снизу и сверху наобум и без привязки к реальной высоте всей таблицы со всеми элементами, так как в таком случае у нас всегда будут возникать артефакты скроллинга. Есть несколько возможных вариантов решить проблему:

1. Каждая строка в списке при выходе за границу видимости рендерит вместо себя пустую заглушку, таким образом у нас экономится очень много ресурсов, так как не придется рендерить кучу лишних DOM-нод в таблице. Этот способ довольно простой, в нем можно делать перерасчет высоты элементов при изменении ширины таблицы. При этом скакать ничего не должно, так как по сути мы не убираем из DOM сами строки, мы просто не рендерим их контент. При этом мы всегда можем рендерить контент строк в области 1.5 видимых областей (по 0.25 сверху и снизу), соответственно мы сможем перепроверять условие показа контента не на каждый scroll event. Минус такого подхода в том, что он медленнее реального virtual scroll и его придется реализовывать самостоятельно, но он проще и не вызывает проблем с высотой. Возможно, такого подхода будет достаточно.
2. Фиксированная высота контейнера. По сути это подход, который использует react-virtalized. В данном случае нам нужно знать высоту всего контейнера (всей таблицы) и кол-во элементов (то есть высота элементов списка не может быть разной). Такой способ будет работать быстрее всего, так как рендерить придется ограниченное кол-во элементов, да и реализовать его будет проще. Но он накладывает определенные ограничения, которые могут полностью свести на нет все эти плюсы на каком-нибудь проекте, где высота строк обязательно должна быть разной.

На мой взгляд, стоит попробовать реализовать первый способ и протестировать на сколько он хорошо решает проблему производительности. Если все же он ее не решит, то уже в таком случае перейти на второй способ.

**Comment by daynin** [comment]
@gizeasy да, рендерятся все. Если уже на этапе первого рендеринга возникают существенные проблемы, то, возможно, этот вариант уже не очень хорошо подходит

**Comment by dmitriykorsakovnedra** [comment]
Попробовали отрендерить таблицу 10x5000 и посчитать высоты строк.
Первый рендер занимает около минуты. Думаю, этот вариант нам не подходит.
