### ISSUE TITLE
Table: сортировка по нескольким столбцам

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#447]

**Comment by fooontic** [comment]
Подумали над двойной сортировкой. Попробовали придумать какое-то решение в рамках компонента таблицы. Пришли к мнению, что двойная сортировка это антипаттерн и крайне специфичное решение, которое не хотим продвигать и затаскивать в компонент таблицы. Поэтому в случае когда бизнес-кейс не позволяет избежать такое решение, мы предлагаем сделать это вне компонента таблицы: добавить кнопку за пределами таблицы. которая открывает попап с настройкой. После применения — таблица перерендериться в соответствии с новыми правилами. Сортировка в самом компоненте таблицы предлагаем отключить, чтобы не путать пользователями сортировкой в разных местах.

Предложенное решение — концепт. В нём не продуманы все крайние кейсы и остаются на усмотрение дизайнера в конкретном кейсе. 

<img width="3496" alt="Double Sort" src="https://user-images.githubusercontent.com/12127740/96694914-b3a43180-1391-11eb-9084-1990e5058d17.png">
Ссылка на предложение в Фигме https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=866%3A34

**Comment by nedradigital** [comment]
> Подумали над двойной сортировкой. Попробовали придумать какое-то решение в рамках компонента таблицы. Пришли к мнению, что двойная сортировка это антипаттерн и крайне специфичное решение, которое не хотим продвигать и затаскивать в компонент таблицы. Поэтому в случае когда бизнес-кейс не позволяет избежать такое решение, мы предлагаем сделать это вне компонента таблицы: добавить кнопку за пределами таблицы. которая открывает попап с настройкой. После применения — таблица перерендериться в соответствии с новыми правилами. Сортировка в самом компоненте таблицы предлагаем отключить, чтобы не путать пользователями сортировкой в разных местах.
> 
> Предложенное решение — концепт. В нём не продуманы все крайние кейсы и остаются на усмотрение дизайнера в конкретном кейсе.
> 
> <img alt="Double Sort" width="2000" src="https://user-images.githubusercontent.com/12127740/96694914-b3a43180-1391-11eb-9084-1990e5058d17.png">
> 
> Ссылка на предложение в Фигме https://www.figma.com/file/u4fDZ5rdcEoJUZ7cITlVJx/Github-issues?node-id=866%3A34

@fooontic Вадим, подскажи, пожалуйста, а сам компонент с контролом для сортировки нужен в UI-ките? Или он всегда будет на уровне проекта, если понадобится?
