### ISSUE TITLE
 TextField: при переполнении скрытие текста в многоточие

### ISSUE THREAD

**Issue by andekhtyar** [gazprom-neft/consta-uikit#461]
Хочется при переполнении импута уводить текст в многоточие, но сделать это не дефолтной настройкой, а модификатором

**Comment by gizeasy** [comment]
@andekhtyar сейчас стандартное поведение инпута, если не вмещается то начало строки уходит за инпут и скрывается. 
Я не совсем понимаю где это может пригодится, допустим в инпут помещается 20 символов на 21 я вижу точки и не вижу что я ввожу. Так получается или я не правильно понял?

**Comment by fooontic** [comment]
Закрываем — инпут так себя вести не должен. Это не нативное поведение.
