### ISSUE TITLE
Добавить возможность ограничивать ширину выпадающего списка в селектах

### ISSUE THREAD

**Issue by c1n1k** [gazprom-neft/consta-uikit#465]
Список растягивается на всю страницу, если значение большое. В консте такое же поведение. Возможно, стоит сделать issue
![](http://s.csssr.ru/UMYJTGU0M/2020-09-23-15-54-01-UpW61.jpg)

**Comment by gizeasy** [comment]
https://github.com/gazprom-neft/consta-uikit/issues/457
