### ISSUE TITLE
Combobox с добавлением новой записи

### ISSUE THREAD

**Issue by dnazarov** [gazprom-neft/consta-uikit#473]
Востребован функционал добавления новой записи в справочник, если таковая отсутствует. 

Пример
![image](https://user-images.githubusercontent.com/4736006/94682410-926d9980-032d-11eb-870f-c31d42b23a61.png)

![image](https://user-images.githubusercontent.com/4736006/94682438-9ef1f200-032d-11eb-834e-dae09ce5d978.png)

**Comment by gizeasy** [comment]
https://consta-uikit.vercel.app/?path=/docs/components-combobox--default-story#%D1%81%D0%B2%D0%BE%D0%B9-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82

под заголовком - свой вариант

**Comment by dnazarov** [comment]
Есть ли событие для добавления новой записи? Для добавления записи необходимо сформировать и отправить запрос к API.
