### ISSUE TITLE
Таблицы: Датапикер в шапке, если в столбце дата

### ISSUE THREAD

**Issue by andekhtyar** [gazprom-neft/consta-uikit#488]
Подумать над фичей: если в столбце формат даты, вместо фильтра у нас был бы в шапке датапикер. В датапикере подсвечиваются даты, которые есть в таблице. Можно выбрать период.

**Comment by andekhtyar** [comment]
от андрея: думаю возможно, сейчас у нас выводится выбор из списка результат которого прокидывается в фильтр. Нам на первый взгляд ни чего не мешает сделать возможность прокидывать кастомный компонент вместо выбора в списке, и также результат смены даты прокидывать в функцию фитрации.

**Comment by fooontic** [comment]
Закрываем по причине объединения в другую задачу #663
