### ISSUE TITLE
Некорректное позиционирование тултипа

### ISSUE THREAD

**Issue by DmitriiBo** [gazprom-neft/consta-uikit#490]
При позиционировании тултипа в направлении upCenter тултип смещен влево и находится немного выше, чем нужно
![Снимок экрана от 2020-10-06 19-02-08](https://user-images.githubusercontent.com/43147386/95231585-ff8c9d80-080b-11eb-8cca-091b78a36fe0.png)

**Также хотелось бы иметь возможность прокинуть className**

**Comment by nekitk** [comment]
Прикрепи скрин из инспектора с элементом, который используется в качестве якоря для тултипа.
Возможно, у него есть левый паддинг, поэтому и позиционируется не по визуальному центру.

**Comment by DmitriiBo** [comment]
@nekitk якорь без паддингов
![Снимок экрана от 2020-10-07 13-50-42](https://user-images.githubusercontent.com/43147386/95321723-20083680-08a4-11eb-916b-9e62c2c93bb8.png)

**Comment by nekitk** [comment]
Для позиционирования якоря используются позиция и размеры элемента в ДОМе (getBoundingClientRect). Трансформ сдвигает содержимое элемента относительно его реальной позиции.

Не думаю, что стоит пытаться поддерживать такие случаи в тултипе. Если не можете отказаться от трансформа, используйте ручное позиционирование тултипа через проп `position`

**Comment by gizeasy** [comment]
добавить в документацию

**Comment by DmitriiBo** [comment]
И можно ли будет добавить поддержку пользовательских className?

**Comment by nekitk** [comment]
@DmitriiBo Заведи отдельный ишью на это. 1 проблема = 1 ишью
