### ISSUE TITLE
Table: Объединение ячеек

### ISSUE THREAD

**Issue by dmitriykorsakovnedra** [gazprom-neft/consta-uikit#499]
В проекте Мероприятия ЦТ и ИТ встретилась таблица с объединенными ячейками.
Было бы неплохо  добавить эту возможность в компонент таблицы.

![image](https://user-images.githubusercontent.com/70529732/95439060-c6fdd880-095f-11eb-9be8-b38a5db7114c.png)

**Comment by dmitriykorsakovnedra** [comment]
@fooontic @gizeasy Коллеги, как по вашему мнению должно настраиваться объединение ячеек?

На скрине видно что не во всех колонках ячейки с одинаковыми значениями объединены. 
Мы собираемся сделать объединение ячеек настройкой каждой колонки таблицы.

Вы согласны или есть другие предложения?

**Comment by gizeasy** [comment]
Кажется что верно думаете. На колонку прокидывать флаг разрешающий объединение в столбце, далее по ячейкам в колонке проверять на одинаковость значений, и если одинаковые то объединять.
