### ISSUE TITLE
TextField: добавить флаг для типа вводимых данных

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#518]
Привет, для `TextField (type="text")` было бы удобно сделать проп dataType с возможными значениями:
"string" | текст
"number" | числа
"mail" | почтовые адреса (к примеру, на деле нам не нужно)
\+какие-то другие типы.

Подразумевается, указание dataType тащит за собой валидацию значения инпута, введенного пользователем, без обработки дополнительных состояний

**Comment by gizeasy** [comment]
думаю что лучше сделать тогда уж валидацию. Сейчас валидацию можно сделать с верху компонента через onChandge, к примеру не давать вводить буквы. Или если value не подходит можно применять модификатор _status

**Comment by kolebayev** [comment]
@gizeasy 
Через onChange быстрое решение, но не полное c т.з. юзабилити.
При неверном типе данных (в числовой инпут вводят текст), интерфейс должен об этом сообщать: например менять свойство state инпута на warning или alert — типичная обратная связь контролов.

Единственный известный мне способ как рулить этим, добавить еще стейт на валидацию текст филда. Тут что для одиночного инпута, что для группы инпутов (например, завернуть инпут в другой компонент, где описана валидация) надо писать дополнительный код для **базовой функциональности**. Поэтому предлагаю сделать флаг

**Comment by gizeasy** [comment]
@kolebayev дело в том что мы не можем диктовать бизнес логику контролов подсвечивать `warning` или `alert`. Это по хорошему делает компонент формы, бывают кейсы когда в зависимости от одного поля нужно подсветить другое или валидация происходит на стороне сервера. По этому обвязку под свои нужды в любом случае писать придется.

**Comment by kolebayev** [comment]
Понял, тогда можно закрыть ишью
