### ISSUE TITLE
MultiCombobox: onCreate вызывает onChange

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#584]
когда проиходит onCreate, после него тут-же срабатывает onChange, это аффектит состояние value.

есть опции типа `{
  name: string;
  category: CategoryIds[];
}`

при `onChange` я добавляю выбранный элемент в `state` и там они у меня все одинокого типа
а при `onCreate` срабатывает onChange в который пробрасывается значение типа `{label: string}`, которое там мне не нужно, и хотелось бы самому когда нужно вызывать onChange со своими параметрами

И вообще кажется что внутреннее состояние `value` у компонента `MultiCombobox` не нужное и только мешается.
Так как всегда его прокидываешь в компонент. Думаю что лучше иметь полный контроль над компонентом.

**Comment by fooontic** [comment]
Исправили в рамках #620
