### ISSUE TITLE
Table: виртуальный "горизонтальный" скролл

### ISSUE THREAD

**Issue by vasilevx** [gazprom-neft/consta-uikit#599]
Добрый день! Столкнулись с тормозящей таблицей с сотней колонок (ПортУ). Хотелось бы иметь возможность их оптимизации по аналогии с виртуальным скроллом для большого количества строк

**Comment by gizeasy** [comment]
О каком кейсе идет речь? кажется пользователь не сможет работать с сотней колонок.

**Comment by dbsergey** [comment]
1. Пользователь инициирует загрузку данных из Excel-документа.
2. Приложение валидирует данные и корректные данные загружает, а некорректные пропускает. 
3. Пользователь просматривает загруженные данные, чтобы 
3.1. Понять, какие данные прошли проверку и были загружены, а какие не прошли и не были. 
3.2. Убедиться, что данные были загружены в приложение корректно. 

См. https://youtu.be/mlIFQlIjTLs

**Comment by gizeasy** [comment]
кажется что с такой таблицей не удобно работать пользователю. И да кейс есть но мы не можем рекомендовать так использовать таблицу. Кажется что вам самим нужно придумать свое решение.

**Comment by fooontic** [comment]
Работать с такой большой таблицей по горизонтали неудобно будет пользователю. Добавить виртуальный горизонтальный скролл мы в принципе можем, но как пользовательский сценарий мы такое не рекомендуем. Поэтому добавление его у нас не приоритете вообще. Тут лучше обратиться к дизайнеру проекта и попросить перепридумать сам сценарий, так как работать с такой таблицей пользователю будет точно неудобно. Возможно нужен какой-то верхнеуровневый дополнительный фильтр. 

@kolebayev кажется ты имеешь отношение к этому проекту, может сможешь что-то подсказать

**Comment by dbsergey** [comment]
Обсудили этот кейс с Ильей, будем переделывать пользовательский сценарий. 
Спасибо.

**Comment by fooontic** [comment]
Вопрос решён
