### ISSUE TITLE
Combobox: Сбрасывать фокус при нажатии вне компонента

### ISSUE THREAD

**Issue by ilchukovaolga** [gazprom-neft/consta-uikit#603]
**Проблема**
При выборе значений из выпадающих списков остается фокус на обоих полях без возможности снять его 
http://s.csssr.ru/UMYJTGU0M/2020-11-12-16-14-17-ODG7z.mp4 

**Как воспроизвести**
1. Перейти в Combobox в Storybook https://consta-uikit.vercel.app/?path=/story/components-combobox--with-create-story 
2. Нажать на иконку стрелки, чтобы появился список
3. Нажать на иконку повторно, чтобы список закрылся
4. Нажать на область вне компонента 

ФР: фокус остался на поле
ОР: фокус с поля снят

**Comment by gizeasy** [comment]
дубль https://github.com/gazprom-neft/consta-uikit/issues/586
