### ISSUE TITLE
Bug: если вызвано много Snackbar'ов, то они сжимаются

### ISSUE THREAD

**Issue by Miocene** [gazprom-neft/consta-uikit#604]
![telegram-cloud-photo-size-2-5301124949605461820-y](https://user-images.githubusercontent.com/7285559/99252259-bfafd180-281f-11eb-92d0-3a45e43ee151.jpg)

**Comment by gizeasy** [comment]
проблема проявляется только в сафари, и связана не с самим компонентом а с его оберткой
