### ISSUE TITLE
Таблица: странный адаптив шапки с фильтрами.

### ISSUE THREAD

**Issue by andekhtyar** [gazprom-neft/consta-uikit#613]
![image](https://user-images.githubusercontent.com/44090737/99951316-fb521a80-2d8e-11eb-91c0-1779b259461e.png)

**Comment by azhadanov** [comment]
![image](https://user-images.githubusercontent.com/38282744/106289866-d4b2d300-625a-11eb-809b-2049ac7313c2.png)

Сейчас не смог воспроизвести данную проблема (на скрине увеличение масштаба в 300%)
