### ISSUE TITLE
Combobox, MultiCombobox: Рефакторинг.

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#619]
* Некоторые общие стили используются только в одном компоненте, надо их перенести.
* ListItem вынести в отдельный компонент
* Убрать внутреннее состояние value, оно только усложняет логику и приемуществ ни каких не добавляет, все равно управление value идет сверху компонента.

**Comment by c1n1k** [comment]
для Combobox и MultiСombobox необходим механизм для управления и получения значения фильтра, т.е. того что вводит пользователь, например необходимо ограничить вводимые значния только числами или строками, возможно когда-то понадобится маска
