### ISSUE TITLE
DatePicker: при указании большого периода в доступных датах (min-max) появляются сильные лаги

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#627]
Заметил такую штуку, если указать двухстолетний период в доступных датах (min-max) то появляются сильные лаги, думаю нужно оптимизировать пересчеты через useMemo и добавить что-то вроде виртуального скрола, чтоб реально отображались элементы только за 3 года, если мы рискуем потерять анимацию слайдера при изменении даты через инпут, то и ладно, оставить ее только по кнопочкам сладера.

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521389483_

**Comment by Lyubavskaya** [comment]
Не актуально
Новый компонент реализован в https://github.com/gazprom-neft/consta-uikit/issues/1166
