### ISSUE TITLE
DatePicker: полностью завязаться на фокус инпута

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#629]
isCalendarOpened  -> calendarFocused полность завязаться на фокус инпута, и в dateControls прокидывать функцию которая сменит состояние calendarFocused

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521355852_

**Comment by Lyubavskaya** [comment]
Реализовано в рамках https://github.com/gazprom-neft/consta-uikit/issues/1166
