### ISSUE TITLE
DatePicker: добавить возможность задавать view, form и state

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#631]
Нужно сделать так чтоб `view`, `form`, `state` можно было задавать у `DatePicker`, ну и типами разрулить чтоб они lоступны были если не использовать свой компонент вместо `TextField`
а на валидацию сделать колбэк у `DatePicker` который бы покидывал `{ error: boolean, errorType: 'noValid' | 'noRealDate'  }`  и далее пользователь уже сам решает как ему отображать эту валидацию

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521343037_

**Comment by Lyubavskaya** [comment]
Не актуально
