### ISSUE TITLE
Calendar: добавить дефолтные значения для minDate, maxDate и currentVisibleDate

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#632]
Относиться к календарю:
currentVisibleDate - это дата текущая, может убрать из обезательных и по дефолту указывать текущюю дату на клиенте?

MinMaxDate - не нравиться что тоже нужно указывать постоянно, может сделаем по дефолту от текущей даты по 100лет в обе стороны?

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521277382_

**Comment by Lyubavskaya** [comment]
не актуально - текущая реализация не требует этого
