### ISSUE TITLE
Calendar: брать названия дней недели из локали и предусмотреть возможность ее смены

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#633]
возможно брать названия из локали? 
и хотелось бы полностью завязаться локаль и предусмотреть возможность смены локали

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521286306_

**Comment by Lyubavskaya** [comment]
Реализовано
