### ISSUE TITLE
DatePicker: добавить inputRef и избавиться от tooltipContent

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#634]
добавить возможность прокидывать в`TextField` `ref` в `DatePicker` пропс будет называться `inputRef`
тултип не нужен, лучше добавить inputRef и уже пользователь сам ели надо накинет на него тултип с нужной инфой

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521358143_
_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521349237_

**Comment by gizeasy** [comment]
Тогда придется сверху учитывать форматирование даты и хендлеры. Вариант через рендер пропс лучше в этом плане. Сразу готовый набор свойств будет прилетать и надо будет только расставить их по местам

**Comment by Lyubavskaya** [comment]
не актуально 
inputRef - Реализовано в рамках https://github.com/gazprom-neft/consta-uikit/issues/1166
