### ISSUE TITLE
DatePicker: заменить тип у onChange

### ISSUE THREAD

**Issue by graberzz** [gazprom-neft/consta-uikit#635]
подумал на будующее `(value: DateRange) => void;` переделать на `(obj:{value:DateRange}) => void;` в дальнейшем проще будет добавить свойств в объект, типа эвент или еще что-то. Да и почти везде из колбека возвращается объект, по этому же принципу.

_Originally posted by @gizeasy in https://github.com/gazprom-neft/consta-uikit/pull/593#discussion_r521280805_

**Comment by Lyubavskaya** [comment]
Реализовано в рамках https://github.com/gazprom-neft/consta-uikit/issues/1166
