### ISSUE TITLE
Table: отображение в Safari

### ISSUE THREAD

**Issue by offtim** [gazprom-neft/consta-uikit#637]
Только в Safari подобное отображение, в chrome норм. [https://consta-uikit.vercel.app/?path=/story/common-about--page](url)
<img width="1438" alt="Снимок экрана 2020-11-27 в 11 58 50" src="https://user-images.githubusercontent.com/18465256/100437788-5303c500-30b2-11eb-83a3-3a41ab5d7d7a.png">

**Comment by fooontic** [comment]
Не удалось воспроизвести в Сафари на других маках.
