### ISSUE TITLE
Badge: Добавление нового функционала (text-overflow)

### ISSUE THREAD

**Issue by dkorsun36** [gazprom-neft/consta-uikit#652]
Добрый день!
В рамках проекта встала задача обрезать текст внутри Badge, добавьте, пожалуйста, возможность обрезания текста если элемент не влезает в строку (можно по умолчанию или через параметр).

![image](https://user-images.githubusercontent.com/75089644/100997030-d9188380-356a-11eb-8b5d-39ae51f04750.png)

**Comment by kolebayev** [comment]
Привет, @dkorsun36
Комопнент состоит из двух информационных слоёв: текст и цвет. Текст говорит _что_ происходит, цвет — _как_, то есть дает качественную оценку. Заведение свойства оверфлоу может создать ситуации с неполным отображением текста, что приведет к неточному считыванию инфы или ошибкам при использовании в других проектах. У нас не получится везде это контролировать, поэтому текстовая часть должна отражаться в бейдже целиком без срезания. Мы не можем затащить эту фичу в UI-kit.

Мы сталкивались с такой ситуацией, могу предложить на выбор:
1. переформулировать длинные текстовые формулировки или сделать аббревиатурами
2. закастомить бейдж на проекте через className, но осторожно, чтобы смысл не разваливался
