### ISSUE TITLE
TextField: при включении autoFocus страница прокручивается вниз

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#660]
Имеется страница на несколько экранов, на самом верху страницы кнопка. По нажатию на кнопку открывается `Modal`, в котором есть `TextField`. Если у него указан `autoFocus`, то в момент отображения `Modal` страница под ним прокручивается до конца вниз. Есди убрать `autoFocus`, эффект пропадает.

**Comment by fooontic** [comment]
@andreynovikov А есть возможность записать видео? не до конца смогли понять ситуацию.

**Comment by andreynovikov** [comment]
Я уже с тех пор перешёл с обычного html списка на Table, но попробую вернуть как было и снять видео.

**Comment by azhadanov** [comment]
![image](https://user-images.githubusercontent.com/38282744/106278289-89dd8f00-624b-11eb-8bbe-50732c97604b.png)

Сымитировал ситуацию указанную в issue - при открытии модального окна, в котором имеется TextField (как с автофокусом, так и без него), страница не прокручивается.
