### ISSUE TITLE
Table: Пожелания разработчиков

### ISSUE THREAD

**Issue by nedradigital** [gazprom-neft/consta-uikit#664]
1. Добавить коллбэк для клика на ряд onRowClick и передать в него все ячейки в ряду 
2. Добавить функцию рендера в колонке, чтобы не передавать компоненты в значениях ячейки
3. Добавить возможность прокинуть в колонку функцию сортировки
4. Сделать поле accessor необязательным для заголовков не последнего уровня

**Comment by fooontic** [comment]
1. Завели отдельную задачу #668 
2. Завели отдельную задачу #669
3. Завели отдельную задачу #670. Возможно будет решено в рамках задачи по переделке фильтрации
4. Завели отдельную задачу #671
