### ISSUE TITLE
Table: Добавить коллбэк для клика на ряд onRowClick и передать в него все ячейки в ряду

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#668]

**Comment by gizeasy** [comment]
нужен более четкий кейс

**Comment by andreynovikov** [comment]
Я тоже такое хочу. Чтобы не кнопки в отдельной колонке делать, а просто нажимать на строку таблицы. Кейс: по клику на строку таблицы открыть модальное окно с более подробным описанием содержимого строки.

**Comment by dmitriykorsakovnedra** [comment]
Кейс по которому завели ишью - Переход на айтем из листа по клику на всю строку
