### ISSUE TITLE
Pagination: правки компонента (случайно влили ПР без дизайн-ревью)

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#678]
1. Кнопок должно быть максимум 10. Сейчас 9. Из-за этого в многоточие упали 8 и 9, хотя в случае 10 страниц многоточие не нужно. 
![image](https://user-images.githubusercontent.com/12127740/102336267-04a36100-3fa2-11eb-9eda-6d2fc404bfea.png)
3. Все подписи должны быть `<Text size="xs" ... />` независимо от размера самой пагинации.
![image](https://user-images.githubusercontent.com/12127740/102336644-809da900-3fa2-11eb-9051-512c5a1af62e.png)
4. Type minified надо переименовать в input или field (как удобнее).
5. В комментарии к ПР писал, что появляется вариант minified и он не то же самое что сейчас называет minified: 
> Появляется новая модификация minified. В ней кнопки Назад и Вперёд появляются только по ховеру и место под них зарезервировано (они скрыты только визуально). Подписей с горячими клавишами у минифицированной версии нет.
Я бы советовал модификатор minified сделать булиновым, чтобы независимо от type он применялся. Потому что у варианта с инпутом, тоже может быть minified, где кнопки со стрелочками тоже появляются только по ховеру.
6. В версии с инпутом — кнопки должны быть тоже с текстом «Назад» и «Вперёд»
![image](https://user-images.githubusercontent.com/12127740/102336934-e2f6a980-3fa2-11eb-8f4b-8827f424c53c.png)
7. Все иконки < > надо заменить на стрелочки (IconForward и IconBackward)
8. Disabled — не нужен вообще такой пропс. Не могу представить себе ситуацию когда может быть необходимость дизейблить всю пагинацию. В таком случае лучше вообще её не показывать. 
9. В версии с инпутом отступ от кнопок со стрелочками должен быть `--space-xs` во всех размерах. Сейчас он меньше
10. Глядя на ЦСС долго пытался понять, что за тултип и где его увидеть. Потом до меня дошло, что это так назвали подсказку о горячих клавишах. Надо бы переименовать везде на просто tip. Tooltip это _всплывающая_ подсказка, тем более путается с нашим компонентом. А Tip это просто подсказка.

Заменили `Alt →` на `Shift →` из-за перекрытия Сторибуком или по другой причине?

**Comment by karpovfv-nedra** [comment]
Я понял, окей, поправлю. Спасибо за замечания.
Alt на Shift заменили да, из-за сторибука, только в примере, он по этим горячим клавишам переключает компоненты в дереве слева, а предотвратить такое поведение сторибука не получилось.

**Comment by karpovfv-nedra** [comment]
@fooontic у меня пара вопросов:
1) я правильно понимаю, что у кнопок назад/вперёд лейблы будут всегда, и в версии minified тоже?
2) в minified версии мы резервируем место для кнопок всегда, или только когда пагинация расположена по центру?

и если подытожить: у нас будет 2 версии пагинации (`default` - с кнопками, `input` - с инпутом, соотвественно); модификатор `minified` будет по сути одинаковым для обеих версий, будут отображаться кнопки назад/вперёд (с лейблами всегда) только по ховеру, и в этом случае подсказки горячих клавиш мы не отображаем?

**Comment by karpovfv-nedra** [comment]
и в каких вообще случаях мы должны резервировать место для кнопок?
