### ISSUE TITLE
Layout: разработать компонент общего лайэута

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#686]
Создать несколько самых популярных шаблонов

**Comment by Lyubavskaya** [comment]
При разработке посмотреть, как реализован компонент в Веге, взять лучшее.

**Comment by schurf-des** [comment]
https://www.figma.com/file/lQJPpOcbtlRk18YSyb6inq/Consta-Charts?node-id=3698%3A1362

**Comment by schurf-des** [comment]
Как компонент не добавляли, составили доку, теперь нужно дать примеры кода с реализацией разных лейаутов.

https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=32810%3A104815
