### ISSUE TITLE
Table: подумать над разворачиванием строк в таблице

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#691]
В идеале собрать пример в доке

**Comment by CustomButtons** [comment]
Здравствуйте. 
Хочу реализовать функционал разворачивания строк в таблице.
В коде это будет выглядеть как расширение типа TableRow и изменения в компонентах Table, TableCell и хелпере Table/helpers.ts  для поддержки вложенных строк
```
export type TableRow = {
  [key: string]: React.ReactNode;
  id: string;
  children?: TableRow[];
};
```
Визуально будет выглядеть примерно так
<img width="1072" alt="table-example" src="https://user-images.githubusercontent.com/5240074/102892197-53109e00-4481-11eb-82c3-53c7345be05b.png">
