### ISSUE TITLE
widgets: Решить, как организовать новую библиотеку виджетов

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#721]
Решить, делаем 2 репозитория (со старой библиотекой и новой) или остается один. 
Пока решили создать мажорную версию. Держим в продакшене 2 версии одновременно -> 2 мастера. Репозиторий Consta-widgest остается один. 
Если 2 репозитория, проверить, можем ли мы понижать версию npm пакета (если вдруг придется обновлять старую библиотеку).

**Comment by gizeasy** [comment]
проверил возможность выкладываться в 1 npm пакет с нескилькими версиями, раюотает!
давайте лучше создадим 2 репозитория, и с них будем выкладывать в 1 npm пакет.

**Comment by Lyubavskaya** [comment]
В рамках этой задачи ещё создадим новый репозиторий consta-widget, переименуем старый в consta-widget-old.
Новый репозиторий почистим от компонентов, создадим 1 тестовый компонент, в котором покажем структуру файлов.
