### ISSUE TITLE
docs: Не ясно, что означают свойства rows и cols в Textfield

### ISSUE THREAD

**Issue by fooontic** [gazprom-neft/consta-uikit#722]
> Количество колонок (ширину) можно указать в свойстве `cols`, а количество строк (высоту) — в `rows`.

Из документации не очень понятно что означают и за что отвечают свойства `cols` и `rows`. Возможно стоит расширить описание

**Comment by azhadanov** [comment]
Вообще, свойства cols и rows - это просто свойства стандартной html-ной textarea. Ни у нас, ни в react-textarea-autosize они никак не обыгрываются.
Но из-за нашего класса .TextField-Input (min-width: 80px;) и прописанную через style высоту в пикселях, размер textarea не совсем напрямую зависит от переданных в него cols/rows.

Итого там сейчас такие свойства отвечают (или должны) за размеры:
minRows={x: number} // минимум строк в высоту (будет рендериться с такой высотой изначально)
maxRows={x: number} // максимум строк в высоту (после преодоления максимума добавится скролл)
cols={x: number} // отвечает за ширину (некорректно работает из-за .TextField-Input (min-width: 80px;))
rows={x: number} // вообще ни на что не влияет (из-за высоты в style, которая прописывается уже в react-textarea-autosize, файл calculateNodeHeight.ts)

Вот хоумпейдж компонента react-textarea-autosize:
https://github.com/Andarist/react-textarea-autosize

**Comment by gizeasy** [comment]
cols - убрать (min-width: 80px; для textarea
minRows = minRows || rows 
maxRows = maxRows || rows
