### ISSUE TITLE
Theme: тёмная тема не задаёт цвет базового фона

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#725]
Если содержимое страницы меньше, чем viewport, то часть фона остаётся светлым. Надо прописать `background-color: var(--color-bg-default)` для `html`, `body`. Если это невозможно, то хотя бы для `.Theme` (он у меня имеет `height: 100vh`)

**Comment by Miocene** [comment]
Привет!
Для `html` и `body` не всегда нужен именно дефолтный цвет. Может быть нужен какой-то из второстепенных или команда может задавать фон для другого dom-узла.

Посмотри как сделал @gizeasy на лендинге 
https://github.com/gpn-prototypes/consta-landing/blob/master/src/containers/App/App.tsx
Тут как раз у html задан фон на проекте и он меняется при смене темы.

**Comment by gizeasy** [comment]
Предоставлена информация о решении проблемы

**Comment by LatikDesu** [comment]
https://github.com/consta-design-system/landing/blob/master/src/containers/App/App.tsx
обновленная ссылка на пример
