### ISSUE TITLE
Theme: стиль прокрутки таблицы в тёмной теме

### ISSUE THREAD

**Issue by andreynovikov** [gazprom-neft/consta-uikit#726]
При включении тёмной темы у компоненты `Table` область прокрутки остаётся светлой, а ползунок вообще не виден.

**Comment by Miocene** [comment]
Можешь приложить скрины и написать браузер и версию?
Не могу воспроизвести

**Comment by andreynovikov** [comment]
Google Chrome 87.0.4280.141 (Official Build)

Тёмный вариант:
![table-scroll-dark-mode](https://user-images.githubusercontent.com/2943625/104160076-8bacf300-5401-11eb-9830-912719c038be.png)

Светлый вариант:
![table-scroll-light-mode](https://user-images.githubusercontent.com/2943625/104160078-8cde2000-5401-11eb-9c57-5db541176522.png)

**Comment by Miocene** [comment]
Так выглядит, потому что у фона страницы не задан цвет. Там браузерный дефолтный белый. Если у обертки страницы задашь нужный цвет `var(--color-bg-default)`, то всё будет ок 👌
