### ISSUE TITLE
BackgroundBarChart,LinearChart: Не проставлены key

### ISSUE THREAD

**Issue by dkorsun36** [gazprom-neft/consta-uikit#734]
Коллеги, добрый день!

В консоли отлавливаем ошибку у компонентов consta по поводу key, данные key не проставлены в компонентах: BackgroundBarChart, LinearChart.
![image](https://user-images.githubusercontent.com/75089644/103271920-95c7fe00-49cc-11eb-8f54-f367a1cf5382.png)

**Comment by gizeasy** [comment]
можете подсказать версию библиотеки и с какими свойствами был вызван компонент?
Я не смог повторить ошибку

**Comment by dkorsun36** [comment]
Версия библиотеки "@consta/widgets": "^3.6.0", примеры компонентов:
![image](https://user-images.githubusercontent.com/75089644/104556955-7af2bc00-5651-11eb-8b9d-3843165737fc.png)
где chartData
![image](https://user-images.githubusercontent.com/75089644/104557033-9b227b00-5651-11eb-8965-e7be861ffc76.png)
LinearChart
![image](https://user-images.githubusercontent.com/75089644/104557193-dd4bbc80-5651-11eb-863b-842cbafc36fb.png)
где chartData
![image](https://user-images.githubusercontent.com/75089644/104557240-f9e7f480-5651-11eb-9459-375e21f6a8f8.png)

**Comment by gizeasy** [comment]
@dkorsun36 опять же не удалось выявить ошибку. Можешь сам поправить и ПРку создать?

**Comment by Lyubavskaya** [comment]
Закрываем в связи с развитием Consta Charts
