### ISSUE TITLE
Attach: кнопки всегда отображаются по наведению

### ISSUE THREAD

**Issue by Miocene** [gazprom-neft/consta-uikit#768]
В коде описано, что кнопка в аттаче всегда видна только по наведению.
В дизайне подразумевалась возможность "закрепить" кнопку. Это важно, например, при загрузке файла и при ошибках. Пользователь должен быстро уметь отменить загрузку или удалить косячный файл.

@fooontic @kolebayev че скажете?

**Comment by Lyubavskaya** [comment]
После реализации Drag'n'dropField будет неактуально.
