### ISSUE TITLE
landing: Корректировки 

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#780]
1. починить снэкбар
2. обратная связь
3. открытие ссылок в новой вкладке
4. ссылка на сайт ГПН на логоблоке
5. логоблок только в разрешенных цветах при переключении тем и компаний
6. картинка с учетом комментария БКК по цвету для разных тем и компаний (после дизайна)
7. добавить ссылку на телеграм-канал (после дизайна)

**Comment by fooontic** [comment]
Разбили по задачам и закрыли ишшью:

1. #795 
2. #796 
3. #794 
4. #793 
5. #797 
6. #798 
7. #791
