### ISSUE TITLE
RadioGroup: Доработать документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#817]

**Comment by arhayka** [comment]
Тут есть вопрос про выбранные радиокнопки. У нас в доке есть пункт, в котором мы рекомендуем сразу выбирать один вариант. Не уверена, что так правильно (хотя рациональное зерно там есть). Если хотим это оставить, стоит во всех примерах в самой доке сделать одну кнопку выбранной.
