### ISSUE TITLE
landing: правки

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#842]
1. Поправить год в тексте лицензии на 2021, открывать его в новом окне (в 2-ух местах).
2. Проверить, что со свитчем (при включении не голубой, а серый).
3. В вопросе "Для каких задач подходит дизайн-система?" поправить "какой-то" на "какой-либо".
4. В вопросе "В какой момент ее лучше подключать?" должна быть точка после "Когда решите сделать прототип или MVP."
5. ! В обратной связи не принимает большие буквы в эл. почте, только маленькие.
6. В футере ссылку на сайт ГПН нужно открывать в новой вкладке.
7. В шапке должно быть GitHub, а не Github
8. Замечания отсюда: https://docs.google.com/document/d/1Y1LBsZ1ZZw__BonEQHze3qqCmVqAWXj0cckqo8Dwazs/edit

**Comment by fooontic** [comment]
- [ ] Поправить год в тексте лицензии на 2021, открывать его в новом окне (в 2-ух местах).
- [ ] Проверить, что со свитчем (при включении не голубой, а серый).
- [ ] В вопросе "Для каких задач подходит дизайн-система?" поправить "какой-то" на "какой-либо".
- [ ] В вопросе "В какой момент ее лучше подключать?" должна быть точка после "Когда решите сделать прототип или MVP."
- [ ] ! В обратной связи не принимает большие буквы в эл. почте, только маленькие.
- [ ] В футере ссылку на сайт ГПН нужно открывать в новой вкладке.
- [ ] В шапке должно быть GitHub, а не Github
- [ ] Замечания отсюда: https://docs.google.com/document/d/1Y1LBsZ1ZZw__BonEQHze3qqCmVqAWXj0cckqo8Dwazs/edit
