### ISSUE TITLE
Modal: Добавить best practices в figma

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#857]

**Comment by Ptitzin** [comment]
Я собрал (какие нашел в проектах) разные виды окошек [тут в фигме](https://www.figma.com/file/l6rdF0guIdH3ZDXSoehuqz/Untitled?node-id=0%3A1). Нужны рекомендации как лучше делать. Где и в какой последовательности ставить кнопки, надо ли заголовок окна, куда ставить крестик.
