### ISSUE TITLE
Theme: Заменить цвета в коде, в трех темах для bg/system и typo/system 

### ISSUE THREAD

**Issue by MariaLakomkina** [gazprom-neft/consta-uikit#882]

**Comment by MariaLakomkina** [comment]
DefaultTheme:
--color-bg-system: color(h(204) s(18) l(89) a(100%)); /* Цвет фона системный */
--color-typo-system: color( h(204) s(28) l(68) a(100%); /* Цвет текста системный*/

DarkTheme:
--color-bg-system: color(h(219) s(8) l(33) a(100%)); /* Цвет фона системный */
--color-typo-system: color(h(219) s(14) l(45) a(100%); /* Цвет текста системный */

DisplayTheme:
--color-bg-system: color(h(213) s(45) l(35) a(100%)); /* Цвет фона системный */
--color-typo-system: color(h(213) s(47) l(47) a(100%); /* Цвет текста системный */

**Comment by Lyubavskaya** [comment]
Делать вместе с https://github.com/gazprom-neft/consta-uikit/issues/1379
