### ISSUE TITLE
Legend: Актуализировать документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#889]

**Comment by arhayka** [comment]
Посмотрела легенду, не вижу изменений. Я что-то пропустила?

**Comment by gizeasy** [comment]
@arhayka

**Comment by schurf-des** [comment]
> 'row' — на одной строке, без переносов,

Не совсем. Он попытается сложить их в строчку без переносов, но если места не хватит — перенесет. Получится такая кирпичная кладочка из айтемов.
—

В остальном норм вроде, все как есть

**Comment by arhayka** [comment]
Поправила это: https://github.com/gazprom-neft/consta-widgets-new/pull/40
