### ISSUE TITLE
StackedBarChart: Актуализировать документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#891]

**Comment by arhayka** [comment]
Хотела посмотреть доку, но не вжиу там изменений (там мой текст, оно нормальный, в сторис примеры вроде совпадают). Подскажи, плиз, тут еще не готово? Если готово, то что поменялось?

**Comment by schurf-des** [comment]
Сейчас там используется термин "группа", что не очень корректно: классический перевод -- столбчатая диаграмма с накоплением, плюс в соседнем барчарте тоже используется этот же термин, но для другого. Путает.
—

Было бы круто их с барчартом по одному принципу описывать, сейчас в одном свойства сначала, в другом в конце
—

Прокрутки и переполнения нет в содержании, есть в оглавлении
—

> Максимальный размер столбика (для одиночных) и группы столбиков (для групповых) зависит от размера контейнера и определяется соотношением. Максимальный размер столбика - 70% от ширины группы.

Как и в барчарте, эта фраза подразумевает знание у человека о том, что внутри график бьется на блоки-контейнеры, по одному на каждую категорию, и вот внутри этого контейнера столбики занимают 70%. Это лишняя какая-то информация, кажется.
—

> По умолчанию график вертикальный.

Либо здесь, либо в доке обычного барчарта ошибка — они строятся на одной базе и не могут работать в этом отношении по разному. Базовое значение isHorizontal = false
—

> Варианты: left, bottom, left-and-bottom, none.

Этого больше нет
—

> Количество делений рассчитывается в зависимости от ширины графика.

...но как и в барчарте можно указать gridConfig ручками и тогда будет плюс-минус то, что ты укажешь. Как работало раньше. Но мы не советуем сильно этим злоупотреблять
—

В барчарте с накоплением не должно быть минусовых значений. Сейчас они там есть, этот косяк надо бы поправить. Но вообще не должно быть

**Comment by arhayka** [comment]
Спасибо, беру в работу

**Comment by arhayka** [comment]
Готово
