### ISSUE TITLE
UserSelect: Разработать документацию

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#905]

**Comment by arhayka** [comment]
https://github.com/gazprom-neft/consta-uikit/pull/1309

**Comment by arhayka** [comment]
Так. Кажется, я сделала это зря: есть новый UserSelect, и он ещё не влит в dev. Жду сигнала.

**Comment by Lyubavskaya** [comment]
Дубль https://github.com/gazprom-neft/consta-uikit/issues/1326
