### ISSUE TITLE
Drag'n'DropField: Разработать компонент

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#912]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=32774%3A0

**Comment by Lyubavskaya** [comment]
https://github.com/gazprom-neft/consta-uikit/issues/768

**Comment by nekitk** [comment]
По показу ошибок решили с Ильёй:
1. Не показывать состояние ошибки во время перетягивания, т.к. у нас нет информации о том, какая именно ошибка и мы не сможем показать правильный текст. В перспективе можно будет доработать react-dropzone, чтобы добавить эту возможность.
2. Ошибки (неправильный размер, неправильный формат и т.п.) показываем в тултипе

**Comment by itsmealbina** [comment]
1. Отличается border-radius для всей области dragndrop
Стенд - 4px, макет - 8px http://s.csssr.ru/UFALX8YMV/20210721_141018.jpg
2.  Не меняется текст и цвет фона при перетаскивании одного/нескольких файлов 
Скрин со стенда http://s.csssr.ru/UFALX8YMV/20210720_185800.jpg, макет https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=34445%3A0
