### ISSUE TITLE
Combobox: Возможность очищать value в input 

### ISSUE THREAD

**Issue by fixmylie** [gazprom-neft/consta-uikit#922]
Сейчас есть кейс в проекте, когда нужно по блюру очистить значение в input, если значение из списка не было выбрано. Т.е человек ввел в input `aaaаааааа`, не выбрал и не создал значение в комбобоксе, ушел с комбобокса, а нам нужно очистить это значение в input
Может стоит добавить возможность прокидывать `inputRef` в компонент или добавить пропс типа `inputValue`?

**Comment by schurf-des** [comment]
Дай плиз ссылочку на кейс в проекте
