### ISSUE TITLE
MultiCombobox: баг при сбросе выбранных значений 

### ISSUE THREAD

**Issue by kolebayev** [gazprom-neft/consta-uikit#925]
Набор выбранных пунктов (массив value в хуке стейта) можно сбросить тремя способами: 
1. клик на крест в инпуте, результат ```value = null```
2. прокликать все бейджи в инпуте, результат ```value = []```
3. прокликать выбранные пункты в выпадающем меню, результат ```value = []```

В нетронутом состоянии компонент имеет ```value = null```, при сбросе мы возвращаемся к нему. Результаты по всем трем пунктам должны быть одинаковы — ```null```

**Comment by kolebayev** [comment]
Мой кейс: ломается фильтрация массива объектов по значениям из MultiCombobox

**Comment by gizeasy** [comment]
Combobox, BasicSelect
