### ISSUE TITLE
User: увеличить высоту строки

### ISSUE THREAD

**Issue by Shupirlik** [gazprom-neft/consta-uikit#927]
![image](https://user-images.githubusercontent.com/24976154/109492535-305fbe80-7a9c-11eb-8c23-c45184d1475b.png)
Увеличить расстояние между именем и подписью, чтобы улучшить читаемость. У подписи обрезаются выносные элементы букв.

**Comment by Lyubavskaya** [comment]
Увеличить расстояние между именем и подписью, чтобы улучшить читаемость. 
У подписи обрезаются выносные элементы букв. - уже реализовано

**Comment by Ilyashis** [comment]
https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=367%3A5636
