### ISSUE TITLE
CollapseGroupItem: Бедж в виде точки занимает лишнее место в фигме

### ISSUE THREAD

**Issue by Ptitzin** [gazprom-neft/consta-uikit#933]
Собственно, на скрине видно, что если слвернуть бедж до точки, то он не становится квадратным, как положено, а занимает бокс дефолтного лейбла в мастере.

Не знаю можно ли это исправить правкой мастера.
<img width="800" alt="CollapsegroupItem в Фигме" src="https://user-images.githubusercontent.com/78861041/109648558-cca4c680-7b6b-11eb-8302-ef3bc599a73a.png">

**Comment by kolebayev** [comment]
Исправлено
