### ISSUE TITLE
landing: Проверить верстку в разных браузерах, поправить

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#942]

**Comment by gizeasy** [comment]
![image](https://user-images.githubusercontent.com/13190808/110541057-49b9d800-8138-11eb-8b4e-9ab2bbbcb172.png)

все проблемы из-за использования clamp
есть люди которые пользуются старыми браузерами(((
у нас clamp используется много где и по этому вот так

https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()

**Comment by kolebayev** [comment]
![2021-03-26 11 03 45](https://user-images.githubusercontent.com/24884175/112601041-fd9eb100-8e22-11eb-9ae8-c63c3f7b1c88.jpg)
