### ISSUE TITLE
storybook: правила оформления issue

### ISSUE THREAD

**Issue by gizeasy** [gazprom-neft/consta-uikit#953]
добавить в storybook  правила оформления issue

**Comment by kolebayev** [comment]
Черновик с описанием общих требований

**Заголовок**

Добавить префикс с принадлежностью ишью. Это может быть название компонента (указывается как в сторибуке), landing (лендос дизайн-системы), storybook, doc и тд. (можно полистать список созданных ишьюс). 
Если не получилось подобрать, будет ок придумать свой или оставить без, потом сами исправим.

Формулировка ишью должна начинаться с Заглавной буквы, быть короткой и отражать суть запроса или предложения. По возможности лучше придерживаться формулировки через действие, например:
`Button: Добавить новый модификатор на размер`
`landing: Исправить цвет в иллюстрации в первом блоке`
`linter: Добавить форматирование md, mdx при комите`

Формулировку ждем на русском языке, англицизмы ок, а вот с английскими словами не увлекайтесь. Эмодзи в заголовке вообще не надо плиз :)

**Комментарий**

Комментарий обязателен для любого автора ишью! Это поможет нам быстрее понять запрос и корректно его оценить, не отвлекая автора.
Покажите свои письменные навыки во всей красе! Картинки или скриншоты? Пожалуйста! Если в форму что-то не прикрепляется (например, svg-иконки), можно прикрепить архив с файлами или оставить ссылку (которая не протухнет через месяц или больше). Ну хотя бы тут можно эмодзи? Мы конечно не против, но бог вам судья.

Объем любой, главное — понятно и по-человечески. Хочется, чтобы в любой момент времени и автору, и исполнителю было понятно что делать. 

**Лейблы**

Если получилось найти подходящий лейбл в списке, ставим твердо и четко. _Кроме лейблов на приоритет!_

**Comment by arhayka** [comment]
https://github.com/gazprom-neft/consta-uikit/pull/1023

**Comment by arhayka** [comment]
Выложено
