### ISSUE TITLE
Table: Добавление новой строки и удаление строки

### ISSUE THREAD

**Issue by dkorsun36** [gazprom-neft/consta-uikit#962]
Коллеги, добрый день!

Очень полезно для пользователей было бы реализовать возможность добавления новой строки в компоненте Table.

Также было бы неплохо реализовать добавление подстроки как на примере:
![image](https://user-images.githubusercontent.com/75089644/110431973-91e8e400-80bf-11eb-9cd7-98552c6a2f43.png)

**Comment by Lyubavskaya** [comment]
Добавить пример

**Comment by dkorsun36** [comment]
При нажатии на кнопку "Добавить секцию" добавлять строку со всеми полями.
Для примера макет с добавлением:
![image](https://user-images.githubusercontent.com/75089644/111455924-7026d700-8727-11eb-8057-c3f62038f238.png)
Так же для удаления новой строки в первой ячейке добавлять кнопку удаления (корзинка), первую строку удалять нельзя

**Comment by gizeasy** [comment]
1) колбек на добавление строки
2) текст кнопки модно менять
3) кнопки удалить либо справа либо слева
4) колбек клик кнопки удаления
5) пример для этого всего
5) пример без 3 и 4 но со своей реализацией кнопки удаления
