### ISSUE TITLE
Tooltip: Доработки тултипа для виджетов

### ISSUE THREAD

**Issue by Lyubavskaya** [gazprom-neft/consta-uikit#965]
1. Инвертнуть, дарковая тема для дефолтного окружения, дефолтная для дарка и дисплея
2. Выровнять цифры по правому краю
3. Сравнять разрядность, если хотя бы у одного значения появляются десятые, они появляются у всех
4. Дивайдер не нужен
5. ~~Если цвет некорректный, должен подставляться дефолтно ghost~~ перенесено в #1024
6. Если прислать пустую строку в название, вся строка исчезает, так не должно быть
7. Нужны тысячные разделители, каждые три символа, считаем от запятой в обе стороны
8. Нужна запятая вместо точки в дробях
9. Нужен минус вместо дефиса
10. Если нет данных, менять кружочек на треугольничек не надо
11. Хотелось бы конечно табличную верстку, чтобы вот такого как на скрине ниже не было
![image](https://user-images.githubusercontent.com/75978078/110462658-046abb80-80e2-11eb-9479-fb20c48b3301.png)

**Comment by gizeasy** [comment]
дизайнер @schurf-des
