### ISSUE TITLE
snackbar: Добавить возможность автоматического закрытия без спинера

### ISSUE THREAD

**Issue by andekhtyar** [gazprom-neft/consta-uikit#972]
Сейчас: 
если включаю autoclose, то включается спинер с обратным отсчётом. Я не могу его убрать и поставить вместо него иконку.

Надо: 
если включаю autoclose, то **я могу** включить спинер с обратным отсчётом, могу и иконку, а могу и без всего.

**Comment by gizeasy** [comment]
Модификатор timer по умолчанию true
