### ISSUE TITLE
Tree: Добавление компонента Дерево

### ISSUE THREAD

**Issue by skillbox-koutja** [gazprom-neft/consta-uikit#973]
Планируется ли добавить в дизайн систему компонент для отображения деревьев/tree. 
Например, подобно этой компоненте
https://www.primefaces.org/primereact/showcase/#/tree

**Comment by Lyubavskaya** [comment]
Дизайн будет добавлен в рамках задачи https://github.com/gazprom-neft/consta-uikit/issues/1709
