### ISSUE TITLE
Table: Странно ведет себя компонент WithButtons в фигме

### ISSUE THREAD

**Issue by Ptitzin** [gazprom-neft/consta-uikit#978]
Компонент Table/L/Cell/WithButtons при вытягивании не ведет себя так же как  Table/L/Cell/Custom   - у него тестовый бокс выравнивается по центру, а у кастомного - по верхней части, поэтому высоту приходится выставлять руками, а не просто hug content.
Ну и хорошо чтобы текстовые блоки выравнивались в компонентах ячеек одинаково.

![IMAGE 2021-03-10 18:19:12](https://user-images.githubusercontent.com/78861041/110652103-1e34fd00-81cd-11eb-878b-30a1350c9051.jpg)
![IMAGE 2021-03-10 18:19:25](https://user-images.githubusercontent.com/78861041/110652140-25f4a180-81cd-11eb-9250-48ee2e6f1dae.jpg)

**Comment by hell0anna** [comment]
поправлено https://www.figma.com/file/v9Jkm2GrymD277dIGpRBSH/Consta-UI-Kit?node-id=1871%3A36244

**Comment by hell0anna** [comment]
@Ptitzin привет! посмотри пожалуйста, все ли ок теперь с ячейкой Table/L/Cell/WithButtons

**Comment by Ptitzin** [comment]
Теперь туда нельзя добавить кнопки, в отличие от компонента Header
![image](https://user-images.githubusercontent.com/78861041/147661571-7ba6f8d7-4518-4904-9519-337747accfe4.png)
Выравнивается все так же  не так как ячейка без кнопок

![image](https://user-images.githubusercontent.com/78861041/147661670-82adb889-dc2d-4410-ab35-9063e37d3d5b.png)

**Comment by hell0anna** [comment]
создали отдельную задачу на добавление кнопок в ячейки, тк изначально такого функционала не было 
https://github.com/gazprom-neft/consta-uikit/issues/1907
