### ISSUE TITLE
BarChart: замечания

### ISSUE THREAD

**Issue by schurf-des** [gazprom-neft/consta-uikit#983]
Начали смотреть в верстке и заполнять примеры [в документации](https://consta-widgets-consta.vercel.app/?path=/docs/components-barchart--minimalistic) и тут повылезали еще замечания
 
- [x] 🔥 Тултип в верстке проваливается за столбики:
![image](https://user-images.githubusercontent.com/75831445/110925582-70dcf900-8334-11eb-812d-3aa5e80679a2.png)

- [x] 🔥 Шкала ездит по экрану:
![image](https://user-images.githubusercontent.com/75831445/110925707-92d67b80-8334-11eb-9bfb-5708544374af.png)

- [x] 🔥 Столбики разной ширины, должны быть всегда одинаковой, даже если в какой-то из групп меньше данных
![image](https://user-images.githubusercontent.com/75831445/110925858-bd283900-8334-11eb-9c03-3d3585d36da6.png)
![image](https://user-images.githubusercontent.com/75831445/110925883-c74a3780-8334-11eb-872b-af6ca3b29dea.png)

- [x] Тултип в вертикальном варианте барчарта вылезает слева от курсора, должен справа
![image](https://user-images.githubusercontent.com/75831445/110925999-ea74e700-8334-11eb-8b42-f03dd9433c00.png)

- [x] Сетка может быть неравномерной, так быть не должно
![image](https://user-images.githubusercontent.com/75831445/110926281-3de73500-8335-11eb-89ad-9a55e1bc88b3.png)

UPD

- [x] Расстояния между группами меньше, чем между барами в группах, так быть не должно. С таким размером баров между ними должен быть 1 пиксель, не больше
![image](https://user-images.githubusercontent.com/75831445/110927656-f8c40280-8336-11eb-829d-548fb2cb24d3.png)

**Comment by Lyubavskaya** [comment]
🔥 Добавить возможность прокинуть onclick на столбец барчарта.
