### ISSUE TITLE
StackedBarChart: замечания

### ISSUE THREAD

**Issue by schurf-des** [gazprom-neft/consta-uikit#984]
https://consta-widgets-consta.vercel.app/?path=/story/components-stackedbarchart--has-ratio

все баги из #983, плюс

- [x] 🔥 Остался кноб для тайтла, которого нет

- [x] 🔥 Расстояние между барами в группах больше, чем между группами. И верхний еще куда-то уехал
![image](https://user-images.githubusercontent.com/75831445/110927105-42f8b400-8336-11eb-92fb-8a13bf740884.png)

- [x] 🔥 Если установить максимум меньше, чем столбик с накоплением, цифра лейбла не должна краситься
![image](https://user-images.githubusercontent.com/75831445/110929006-8c4a0300-8338-11eb-8db9-d78c985d0b96.png)

- [x] 🔥 Если установить максимум меньше, чем столбик с накоплением, его части должны сохранять свои пропорции. На скрине максимум 100, синяя полоска должна заполнять весь бар и уходить в градиент, не важно что там еще есть
![image](https://user-images.githubusercontent.com/75831445/110927408-a5ea4b00-8336-11eb-8393-6add81405f3c.png)

- [x] 🔥 Значения с минусом не должны показываться
![image](https://user-images.githubusercontent.com/75831445/110927514-c914fa80-8336-11eb-8aff-95130e5b2a86.png)

- [x] градиент должен быть всегда шириной (или высотой, если вертикальный) 16. 
![image](https://user-images.githubusercontent.com/75831445/110929310-e4810500-8338-11eb-95c7-236a37707e0a.png)

**Comment by Lyubavskaya** [comment]
🔥 Добавить возможность прокинуть onclick на столбец барчарта.
