### ISSUE TITLE
LinearChart: доработка сторибука

### ISSUE THREAD

**Issue by schurf-des** [gazprom-neft/consta-uikit#986]
По сторям все хорошо и много, но очень хотелось бы вынести в кнобы больше параметров. Сейчас условные минимум и максимум оси нельзя из сторибука поменять, хотя вариант отрисовки с их использованием есть. В итоге ты заходишь и, не зная что такая опция вообще возможно, можешь сходу не понять а что вообще изменилось.

Для первого релиза можно вынести в каждую только то, что отличается от дефолтных настроек в рамках конкретной. Иначе будет полотно в каждой. Но по хорошему это нужно переработать концептуально. Обсуждали с @gizeasy и решили это оставить на недалекое будущее.

**Comment by Lyubavskaya** [comment]
В связи с остановкой развития consta widgets и переходом на Charts не актуально
