### ISSUE TITLE
Table: Глубокая проверка данных таблицы для mergeCells

### ISSUE THREAD

**Issue by dkorsun36** [gazprom-neft/consta-uikit#987]
Добрый день!

Прошу добавить глубокую проверку в компонент Table чтобы при передаче в нее функции с данными, если данные были одинаковы, то ячейки схлопывались.

Как передаем редактируемый компонент для таблицы:
![image](https://user-images.githubusercontent.com/75089644/111135825-2951a980-858e-11eb-9fa4-1afecc264d3d.png)

Какое поведение ожидаем от таблицы если внутри введены одинаковые данные:
![image](https://user-images.githubusercontent.com/75089644/111135953-48e8d200-858e-11eb-9f9d-1c618c6d26a3.png)

Место где происходит проверка в consta-ui:
![image](https://user-images.githubusercontent.com/75089644/111136053-5bfba200-858e-11eb-92c8-ebe876d41c68.png)

**Comment by gizeasy** [comment]
Думаю что лучше передавать флаг объединения

**Comment by dkorsun36** [comment]
Возможно флаг объединения поможет в этой ситуации.

**Comment by gizeasy** [comment]
Проверить возможно ли сделать как на скриншете через renderCell, то есть сравнение будет происходить по значению, а после объединения вывод данных произойдет через renderCell

**Comment by gizeasy** [comment]
функция проверки 
(colName: string,{a: cell, b: cell}) => true
