### ISSUE TITLE
doc: разделение документации

### ISSUE THREAD

**Issue by schurf-des** [gazprom-neft/consta-uikit#991]
В фигме оставляем только то, что касается технической стороны работы с фигмой. 
Остальные рекомендации по компонентам нужно отнести в сторибук.

**Comment by Lyubavskaya** [comment]
По работе с большими компонентами пошаговое описание в Figma
Если в Figma есть полезное описание для разработчиков - перенести его в Сторибук

**Comment by Lyubavskaya** [comment]
Будем делать в рамках реализации нового портала Figma
