### ISSUE TITLE
Textfield и Select: Компонент меняет свой размер при включении состояния alert

### ISSUE THREAD

**Issue by Ptitzin** [gazprom-neft/consta-uikit#993]
При включении состояния error компонент становится больше, в результате, если находится в auto layout, то он сдвигает все остальные поля
![image](https://user-images.githubusercontent.com/78861041/111796941-be7bd780-88d9-11eb-9e94-c16420fb183e.png)

В результате все слишком сильно сдвигается и образует отгромные дыры, приходится все поправлять руками. /
Вот я нарисовал пример.
![image](https://user-images.githubusercontent.com/78861041/111798563-3e567180-88db-11eb-81b4-a3c19b0ebea4.png)

**Comment by kolebayev** [comment]
Попробуй собрать форму целиком на auto layout, включая фон. будет ок
