### ISSUE TITLE
Snackbar: Добавляем возможность передавать разметку текста

### ISSUE THREAD

**Issue by andekhtyar** [gazprom-neft/consta-uikit#997]
Добавляем возможность передавать разметку текста. Не всё, что угодно (то есть картинку передавать в снекбар нельзя), а именно разметку.

**Comment by Lyubavskaya** [comment]
Научиться, чтобы текст мог быть жирным или сделать ссылку

**Comment by gizeasy** [comment]
По факту поменять тип свойства message у элемента. и поставить проверку на React.node если React.node то выводим его как есть если строка или число то оборачиваем в Text
